### ISSUE TITLE
Some updates ignored

### ISSUE THREAD

**Issue by softforseeker** [alik0211/mtproto-core#103]
In the latest version, I found that some updates are being ignored. In particular, when RPC receives a message with the predicate 'mt_rpc_result' and result field includes predicate 'mt_gzip_packed', some updates can be ignored. Problem lines:

https://github.com/alik0211/mtproto-core/blob/e4fc9e1b370d8557c3d2639673aafb97aba1c0eb/src/rpc/index.js#L506-L527

**Comment by alik0211** [comment]
Thank you very much for your attention. Fixed — https://t.me/mtproto_core/22
