### ISSUE TITLE
How to use this lib in the browser?

### ISSUE THREAD

**Issue by krisztianbkertesz** [alik0211/mtproto-core#107]
Description says it's for the browser and node.js. I tried to set it up with Browserify, but it gives me an error since it uses the Fs module...

`Uncaught TypeError: fs.statSync is not a function`

**Comment by LeonardoRick** [comment]
Could you show your implementation? I think I'm having the same issue

**Comment by krisztianbkertesz** [comment]
To be honest it was an urgent thing for me to solve and so I moved on to another solution. I found TaaS, which is a rest api to access Telegram's api. It's free to an extent, and very affordable beyond the limit too.

**Comment by alik0211** [comment]
If you want to use this library in the browser, use the webpack. I will add Browserify support later.

**Comment by superDoss** [comment]
Could you elaborate on how to use this in the browser?

**Comment by alik0211** [comment]
Update the library to version 6 and use import for browser - https://mtproto-core.js.org/docs/#import-for-browser-environment
