### ISSUE TITLE
Proper usage of `channels.editAdmin`

### ISSUE THREAD

**Issue by ofs904** [alik0211/mtproto-core#108]
Hey, can you please give an example of usage for `channels.editAdmin`.

Currently trying in this way:
```
const params = {
    channel: {
        _: 'inputChannel',
        channel_id: `%an id%`,
        access_hash: '%a hash%',
    },
    user_id: {
        _: 'inputUser',
        user_id: `%an id%`,
        access_hash: `%an hash%`,
    },
    rank: 'test123',
    admin_rights: {
        _: 'chatAdminRights',
        anonymous: true,
    }
};

API.call('channels.editAdmin', params)
    .then((result) => {
        console.warn(result);
...
```

Gives this response:
```
{
  _: 'updates',
  updates: [],
  users: [],
  chats: [
    {
      _: 'channel',
      ...rest channel data...
    }
  ],
  ...
}
```

and nothing changes for given user.
I'd like to make a user admin with the only `anonymous` right.

**Comment by softforseeker** [comment]
`anonymous` property was added in latest layer (117)
You must use [constructor](https://core.telegram.org/constructor/chatAdminRights)  for layer 113

**Comment by alik0211** [comment]
I plan to update the layer in the next release.

You can follow future releases in the official Telegram channel — https://t.me/mtproto_core
