### ISSUE TITLE
How to pass parameters to a constructor?

### ISSUE THREAD

**Issue by DamiToma** [alik0211/mtproto-core#109]
(I completely changed the title because I realized I was calling the wrong method. Still, calling a non-existing method raises an unhandled rejection.)

I'm trying to get the list of channel members using `channels.getFullChannel`. It requires a channel parameter of type `InputChannel`, which also requires two different parameters, `channel_id `and `access_hash`. I can pass a constructor using:

  ```
mtproto.call('channels.getFullChannel', {
    channel: {
      _: 'inputChannel'
    }
  }).then(result => {
    console.log(result);
  }).catch(console.trace);
```

But what if I also want to pass parameters to the constructor?

**Comment by pokearaujo** [comment]
Hi,

Try

```
mtproto.call('channels.getFullChannel', {
  channel: {
    _: 'inputChannel',
    channel_id: ID_CHANNEL_HERE,
    access_hash: ID_CHANNEL_ACCESS_HASH
  }
}).then(result => {
  console.log(result);
}).catch(console.trace);
```

**Comment by DamiToma** [comment]
Works, thanks a lot.
