### ISSUE TITLE
not receiveing private messasgens on 'updates' listener

### ISSUE THREAD

**Issue by LeonardoRick** [alik0211/mtproto-core#111]
I don't know whats happening but I'm not receveing private messagens on this listener that I'm think is supposed to receive all updates on telegram. 

```
        this.tlg.updates.on('updates', (msg) => {
          console.log(msg);
        });
```

I'm looking for just text updates and I do receive it when it's a group `(updateNewMessage)` or a channel `(updateNewChannelMessage)`. But when I't a private message I'm receiveing nothing. Am I missing something?

**Comment by alik0211** [comment]
Most likely, the update you need comes in another [Updates](https://core.telegram.org/type/Updates). Add an `.on` for all [Updates](https://core.telegram.org/type/Updates): updatesTooLong, updateShortMessage, updateShortChatMessage, updateShort, updatesCombined, updates, updateShortSentMessage

I plan to make a guide for listening to updates. Follow this in the official Telegram channel — https://t.me/mtproto_core
