### ISSUE TITLE
[QUESTION] how to get user id based on number?

### ISSUE THREAD

**Issue by LeonardoRick** [alik0211/mtproto-core#112]
I'm currently using this call to check if user is logged:

```
mtproto
    .call('users.getFullUser', {
      id: {
        _: 'inputUserSelf',
      },
    })
    .then(response => {
      // The user is logged in.
      return true;
    })
    .catch(error => {
      // The user is not logged in.
      return false;
    });
```

The problem is that any user authenticated will return true, doesn't matter if another user is trying to use my application from the same machine. I saw on the [official docs](https://core.telegram.org/method/users.getFullUser) that is possible to send a `id` being the user id that we wan't to get full information. 

I already have the user phone number but I couldn't find a way to get his `user id` to allow me send this id on `getFullUser` call.

Is there a way to retrive the user `id` with his phone number? I saw [this website](https://www.callmebot.com/get-telegram-id-from-phone-number/) that does exactly it so probably it's possible.

Otherwise I'm not able to log new users if one another is logged in.

Thanks a lot!

**Comment by LeonardoRick** [comment]
@alik0211 could you please give me some light here? I think it's not that hard to do that, but I can't find a way and it's very important for me.

**Comment by pokearaujo** [comment]
Hi,

What i do:

First import the contacts
```
    const useradded= await this.call('contacts.importContacts', {
      contacts: [
        {
          _: 'inputPhoneContact',
          client_id: 123456, // your internal client id, can be anything
          first_name: 'Bem loco', // client name
          phone: '+5515998xxxxxxx', // phone
        },
      ],
    });
```
In result will have "id" and "access_hash"

After you can delete the user

```
   const deleted = await this.call('contacts.deleteContacts', {
      id: [
        {
          _: 'inputUser',
          user_id: ID,
          access_hash: ACCESS_HASH,
        },
      ],
    });
```

**Comment by alik0211** [comment]
@pokearaujo answer solves this problem.
