### ISSUE TITLE
updateInitConnectionParams is not in .d.ts

### ISSUE THREAD

**Issue by dmitryrn** [alik0211/mtproto-core#113]
Am I missing something or type definition is not complete?

also syncAuth, setDefaultDc, createRPC

**Comment by alik0211** [comment]
syncAuth, createRPC - non-public methods
setDefaultDc - https://github.com/alik0211/mtproto-core/blob/master/index.d.ts#L23

updateInitConnectionParams - good point. I will add it in future releases
