### ISSUE TITLE
Delete message from chat

### ISSUE THREAD

**Issue by tavriaforever** [alik0211/mtproto-core#119]
Hi! 

I`m trying to delete all chat history by using https://core.telegram.org/method/messages.deleteHistory

**Code**
```js
    deleteChatHistory = async() => {
        const deletedHistory = await api.call('messages.deleteHistory', {
            just_clear: false,
            revoke: false,
            peer: {
                _: 'inputPeerChat',
                chat_id: <here chat id>,
            }
        });

        console.log('deletedHistory', deletedHistory);

        return deletedHistory;
    }
```

**API answer** 
```js
deletedHistory { _: 'messages.affectedHistory', pts: 69, pts_count: 2, offset: 0 }
```

**Result**

The history was deleted only for the user from under which I execute the request, all other participants have the message history left. This is probably not how I specify flags

**Comment by alik0211** [comment]
Unfortunately, you can't delete the history for all participants using the `messages.deleteHistory` method.

Replace: delete each message from the chat using the [`messages.deleteMessages`](https://core.telegram.org/method/messages.deleteMessages) method.

**Comment by alambertt** [comment]
> Unfortunately, you can't delete the history for all participants using the `messages.deleteHistory` method.
> 
> Replace: delete each message from the chat using the [`messages.deleteMessages`](https://core.telegram.org/method/messages.deleteMessages) method.

I'm trying to delete a message from a chat but it doesn't work. Any example??
