### ISSUE TITLE
question about access_hash

### ISSUE THREAD

**Issue by iamDonkey** [alik0211/mtproto-core#120]
hi @alik0211 Thanks for the great library.
i checked access_hash that i i am getting from mtproto core and another library called madelineproto for same peers.
while all positive access_hash numbers got from both library matching but not with negative sign. 
mtproto core does not give negative signed access_hash at all. 
here it says  https://docs.madelineproto.xyz/API_docs/types/long.html 
long = A 64 bit signed integer ranging from -9223372036854775808 to 9223372036854775807 
can you enlighten me what  i am missing?

**Comment by alik0211** [comment]
Why do you compare `access_hash` in different libraries?

The decimal representation of a number doesn't matter.

**Comment by iamDonkey** [comment]
> Why do you compare `access_hash` in different libraries?
> 
> The decimal representation of a number doesn't matter.

i wanted to check access_hash varies on session/account level. 

i got `-6813863586994958762` for a peer in madelineproto and in mtproto core for the same peer its `11632880486714592854` in any way `11632880486714592854` can be converted to `-6813863586994958762` or vice versa? :thinking:

**Comment by IRGC** [comment]
Hmm
