### ISSUE TITLE
Sometimes WebSocket closing state and request failed

### ISSUE THREAD

**Issue by Metallistener** [alik0211/mtproto-core#121]
Hi! I don't know it's a bug or what, but sometimes WebSocket close state and request failed and you need to reload application to do request again and again. First WebSocket onopen event triggered then after it trigger onclose event and state is closing
<img width="905" alt="Снимок экрана 2020-11-13 в 00 25 05" src="https://user-images.githubusercontent.com/33493261/98986614-f7c8c300-2546-11eb-9f2a-6ef6e8e2e652.png">

**Comment by softforseeker** [comment]
#91

**Comment by Metallistener** [comment]
> #91

I cannot use TCP transport in browser type, so I se Socket (WebSocket) and it fails requests cause it close connection

**Comment by alik0211** [comment]
Network issues fixed in version 5.2.0 - https://t.me/mtproto_core/25
