### ISSUE TITLE
Request to change chat rights throuth editChatDefaultBannedRights method

### ISSUE THREAD

**Issue by bedrew** [alik0211/mtproto-core#122]
Hi, please help me compose request to set view_messages right to true, after creating chat.

I suppose it looks something like this, but banned_right section...

 api.call('messages.editChatDefaultBannedRights', {
        peer: {
            _: 'inputPeerChat',
            chat_id: chatId,
        },
        banned_rights: 
  })

Thanks

**Comment by alik0211** [comment]
Just set `view_messages` to `true`:

```js
api.call('messages.editChatDefaultBannedRights', {
  peer: {
    _: 'inputPeerChat',
    chat_id: chat_id,
  },
  banned_rights: {
    _: 'chatBannedRights',
    view_messages: true,
  },
});
```
