### ISSUE TITLE
How to get access_hash of private channel ?

### ISSUE THREAD

**Issue by robinvrd** [alik0211/mtproto-core#124]
In all methods using channel as parameter, `channel_id` and `access_hash` are required. But for a private channel, it seems impossible to use `contacts.resolveUsername` to retrieve `access_hash` as a private channel has no username.

How can I retrieve `access_hash` to use channels related methods then ?

**Comment by Alekov** [comment]
For obtaining channel_id and channel access_hash you can use messages.checkChatInvite with hash param, that can be obtained from invite link (t.me/joinchat/hash).

**Comment by LennyLip** [comment]
@Alekov This method does not work for bots, do you know the analogue method for bots? Thanks.
