### ISSUE TITLE
Getting updates

### ISSUE THREAD

**Issue by mytecor** [alik0211/mtproto-core#125]
How can I receive updates using bot account?
<details>
<summary>The code I tried</Summary>

```js
let { MTProto } = require('@mtproto/core')

const api = new MTProto({
  api_id: process.env.API_ID,
  api_hash: process.env.API_HASH
})

api.call('auth.importBotAuthorization', {
  bot_auth_token: process.env.BOT_TOKEN
})

api.updates.on('updatesTooLong', console.log)
api.updates.on('updateShort', console.log)
api.updates.on('updateShortMessage', console.log)
api.updates.on('updateShortChatMessage', console.log)
api.updates.on('updateShortSentMessage', console.log)
api.updates.on('updatesCombined', console.log)
api.updates.on('updates', console.log)
```
</details>

**Comment by pogudin-sergey** [comment]
How can I receive updates? Messages is sended, updates do not receive!

`
let { MTProto } = require('@mtproto/core')

const api = new MTProto({
  api_id: process.env.API_ID,
  api_hash: process.env.API_HASH,
  test: false,
  customLocalStorage: storage
})

api.updates.on('updatesTooLong', console.log)
api.updates.on('updateShort', console.log)
api.updates.on('updateShortMessage', console.log)
api.updates.on('updateShortChatMessage', console.log)
api.updates.on('updateShortSentMessage', console.log)
api.updates.on('updatesCombined', console.log)
api.updates.on('updates', console.log)
`

**Comment by alik0211** [comment]
For the user, use the code from the documentation - https://mtproto-core.js.org/docs/setup-handle-updates

Documentation of the use of the bot account in the process. Follow the updates in the official Telegram channel - https://t.me/mtproto_core
