### ISSUE TITLE
Create Telegram account 

### ISSUE THREAD

**Issue by inayatu** [alik0211/mtproto-core#128]
Is it posssible to create new Telegram account using [mtproto-core ](https://github.com/alik0211/mtproto-core/) ?  If not what are the limitations?

**Comment by Andriy2** [comment]
Yes, you can create account using this module. 
Related methods: `auth.sendCode`, `auth.signUp`

**Comment by meylisatamuradov** [comment]
> Yes, you can create account using this module.
> Related methods: `auth.sendCode`, `auth.signUp`
I also trying to create an account using this module. I am always getting error phone code invalid. I guess this is because of terms of service. But I don't know how to do this. If you don't mint that would be great if you provide a little of example step by step

**Comment by alik0211** [comment]
@inayatu of course, just use this method - https://core.telegram.org/method/auth.signUp
