### ISSUE TITLE
A simple library

### ISSUE THREAD

**Issue by MusiCode1** [alik0211/mtproto-core#130]
Is there a ready-to-use library based on this library?
With ready-made methods for sending messages, etc.

The advantage of the directory is that it surpasses the others that have simple interfaces that do not need the binaries.

Thanks.

**Comment by alik0211** [comment]
i didn't understand your question. you can send any method using [`mtproto.call`](https://github.com/alik0211/mtproto-core#mtprotocallmethod-params-options--promise). Examples - https://github.com/alik0211/mtproto-core/blob/master/docs/authentication.md

**Comment by MusiCode1** [comment]
Okay.
Is there a library ready for simple use, like Python has the telethon.

This library can be likened to low-level programming, while telethon is high-level programming, which is simpler.

**Comment by alik0211** [comment]
This is not a low-level programming library.
