### ISSUE TITLE
Cannot find module node_modules/pako/lib/inflate with es modules

### ISSUE THREAD

**Issue by mytecor** [alik0211/mtproto-core#131]
Can be fixed by adding .js after `pako/lib/inflate` in `src/tl/deserializer/index.js`:
```js
import { inflate } from 'pako/lib/inflate.js';
```

**Comment by mytecor** [comment]
Can be fixed by adding .js after `pako/lib/inflate` in `src/tl/deserializer/index.js`:
```js
import { inflate } from 'pako/lib/inflate.js';
```

**Comment by alik0211** [comment]
Are you using the library in the browser or in node js?

**Comment by alik0211** [comment]
Also, what version of the library are you using?

**Comment by mytecor** [comment]
5.2.0 in nodejs 15.3.0

**Comment by mytecor** [comment]
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '\node_modules\pako\lib\inflate' imported from \node_modules\@mtproto\core\src\tl\deserializer\index.js
Did you mean to import pako/lib/inflate.js?
```

**Comment by alik0211** [comment]
1. Use only the even version of node js
2. Update the library to the latest version
