### ISSUE TITLE
Send Message to Channel

### ISSUE THREAD

**Issue by mominak47** [alik0211/mtproto-core#134]
I am trying so hard to send a message to the channel owned by the user. Can you please write a proper syntax for me. I have the id of the channel.

**Comment by alik0211** [comment]
Attach your code.

**Comment by mominak47** [comment]
Thanks for the response Ali but now it is working fine.

**Comment by LeonardoRick** [comment]
@mominak47 anyway, would be nice to see your solution working and what was your challenge
