### ISSUE TITLE
Need help with channels.getParticipants

### ISSUE THREAD

**Issue by Alekov** [alik0211/mtproto-core#137]
Hello! Is there a way to get more than 200 participants from a telegram channel?

I'm using the following code:
```javascript
async function getAndSaveParticipants(data) {
	const inputChannel = {
		_: 'inputChannel',
		channel_id: data.id,
		access_hash: data.access_hash
	};

	let offset = 0;
	while (true) {
		const getParticipants = await mtproto.call('channels.getParticipants', {
			channel: inputChannel,
			filter: {
				_: 'channelParticipantsSearch'
			},
			offset: offset,
			limit: 100
		});

		if (getParticipants.users.length > 0) {
			await saveUsersToFile(getParticipants);
			offset = offset + getParticipants.users.length;
		} else {
			break;
		}
	}
}
```
This i'm recieving after the last chunk of users:
```
{
  _: 'channels.channelParticipants',
  count: 200,
  participants: [],
  users: []
}
```

**Comment by Alekov** [comment]
Looks like server-side limit.

**Comment by brantian** [comment]
@Alekov did you manage to solve this problem?

**Comment by caioagiani** [comment]
@Alekov @brantian Did you solve this problem?

**Comment by brantian** [comment]
@caioagiani no, unfortunately. I dont think there's a solution for that because it's a limitation on the Telegram product. Even on the mobile app, you can't see more than 200 participants for a channel even if you own it
