### ISSUE TITLE
Error while using upload.getFile

### ISSUE THREAD

**Issue by arghyac35** [alik0211/mtproto-core#138]
I am trying to download file, I am using the below code to getFile, but its is giving error: `Cannot destructure property 'length' of 'bytes' as it is undefined`
```
    await api.call("upload.getFile", {
      cdn_supported: false,
      precise: false,
      offset: 0,
      limit: 4096,
      location: {
          _: "inputDocumentFileLocation",
          id: msg.reply_to_message.document.file_id,
      },
  }).catch((error: any) => console.error(error.message));
```

Can you please guide me what is the correct way to use this method?

**Comment by alik0211** [comment]
@arghyac35 use official docs - https://core.telegram.org/api/files

Or wait until I write the guide
