### ISSUE TITLE
Storage ERR (localStorage is not defined)

### ISSUE THREAD

**Issue by DudoMan** [alik0211/mtproto-core#14]
![Code_2020-03-31_16-25-11](https://user-images.githubusercontent.com/21123136/78031447-3e78fc80-736c-11ea-960f-2c69a0092dd0.png)
))

**Comment by DudoMan** [comment]
Index.js =>> example code (and My auth data)

**Comment by alik0211** [comment]
The current version of the library is only compatible with the browser (localStorage is not included in NodeJS). I will add support for Node JS in the next versions

**Comment by alik0211** [comment]
Follow the development of this feature in #15

**Comment by DudoMan** [comment]
Very Good! Thanks!
