### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by egocentrist** [alik0211/mtproto-core#141]
I'm trying to connect to two accounts at the same time.
When calling the second instance of MTProto, I get the answer exacly as from the first one.
How i can fix it?

```javascript
const { MTProto } = require('@mtproto/core');
const { LocalStorage } = require('node-localstorage');

async function test () {

  const api_id = 'change_me'
  const api_hash = 'change_me'
  const customLocalStorage = new Storage('change_me') //need to be pre-auth

  const mtproto1 = new MTProto({
    api_id,
    api_hash,
    customLocalStorage
  });

  const mtproto2 = new MTProto({ //new session
    api_id,
    api_hash
  });

  try {
    await mtproto1.call('users.getFullUser', { id: { _: 'inputUserSelf' } })
    console.log('Got mtproto1 res, good');
  } catch (error) {
    console.log('Fail mtproto1 res, bad', error);
  }

  try {
    await mtproto2.call('users.getFullUser', { id: { _: 'inputUserSelf' } })
    console.log('Got mtproto2 res, bad');
  } catch (error) {
    console.log('Fail mtproto2 res, good', error);
  }

  process.exit()
}

class Storage {
  constructor(path) {
    this.localStorage = new LocalStorage(path)
  }
  setItem (key, value) {
    return this.localStorage.setItem(key, value)
  }
  getItem (key) {
    return this.localStorage.getItem(key)
  }
}

test()

```

**Comment by alik0211** [comment]
Please use English

**Comment by egocentrist** [comment]
> Please use English

edited

**Comment by bragovo** [comment]
I need the same thing, but as I know (https://github.com/alik0211/mtproto-core/pull/129 https://github.com/alik0211/mtproto-core/issues/88 and some others) Alik don't want to implement this.

@alik0211 why you don't want to add this? `customLocalStorage` didn't help because there is a global cache object there. It's a really useful thing for a lot of people. Maybe we can help you to add this?

**Comment by egocentrist** [comment]
> I need the same thing, but as I know (#129 #88 and some others) Alik don't want to implement this.
Thank you, bragovo!
You pointed me to SergeyFromHell's answer. Using it, I modified the built-in Storage and loaded it by extending the MTProto module.
As for the existence of the indicated problem, I suppose that this is some kind of protection from spammers and others.

**Comment by atiquefiroz** [comment]
@egocentrist can you help me with the same, i have the same requirement. It will be helpful.

**Comment by alik0211** [comment]
The library does not support multiple connections. Perhaps support will be added in the future. Follow the changes in the official Telegram channel - https://t.me/mtproto_core
