### ISSUE TITLE
Change DC2 ip

### ISSUE THREAD

**Issue by sg-4xxi** [alik0211/mtproto-core#144]
Change DC2 ip to 149.154.167.50
https://github.com/alik0211/mtproto-core/blob/4c40bd541bc15ae4b07cc57bb4c6fdb9aa9edc90/src/index.js#L34

**Comment by alik0211** [comment]
Good point, I'll do it in the next version.

**Comment by alik0211** [comment]
Published in version 6.0.0 - https://t.me/mtproto_core/29

Thank you!
