### ISSUE TITLE
How to invite users into a group?

### ISSUE THREAD

**Issue by pawangspandey** [alik0211/mtproto-core#147]
Hi there,
I am trying to invite users into a group but during calling `call` function it is throwing error
```
0|index    | TypeError: Cannot read property 'call' of undefined
0|index    |     at Counter.predicate (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/tl/counter/index.cjs:101:8)
0|index    |     at Counter.channels.inviteToChannel (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/tl/builder/index.cjs:5883:10)
0|index    |     at Counter.predicate (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/tl/counter/index.cjs:101:8)
0|index    |     at Counter.initConnection (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/tl/builder/index.cjs:5625:10)
0|index    |     at Counter.predicate (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/tl/counter/index.cjs:101:8)
0|index    |     at Counter.invokeWithLayer (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/tl/builder/index.cjs:5670:10)
0|index    |     at new Counter (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/tl/counter/index.cjs:7:8)
0|index    |     at new Serializer (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/tl/serializer/index.cjs:7:21)
0|index    |     at RPC.call (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/rpc/index.cjs:581:24)
0|index    |     at MTProto.call (/home/ubuntu/telegram_api2/node_modules/@mtproto/core/src/index.cjs:81:28)
``` 

I am not sure what I am sending wrong in the params.
```js
mtproto.call('channels.inviteToChannel', {
"channel": {
           "_": "InputChannel",
           "channel_id": "Channel ID",
           "access_hash": "XXXXX"
       },
       "users":[
           {
               "_": "InputUser",
               "user_id": "User Id",
               "access_hash": "XXXX"
           }
       ]
})
```
Here is the documentation on `channels.inviteToChannel`  https://core.telegram.org/method/channels.inviteToChannel
Please Help..

**Comment by josselyncolombet** [comment]
`mtproto.call('channels.inviteToChannel', {
"channel": {
           "_": "inputChannel", //here
           "channel_id": "Channel ID",
           "access_hash": "XXXXX"
       },
       "users":[
           {
               "_": "inputUser", //here 
               "user_id": "User Id",
               "access_hash": "XXXX"
           }
       ]
})`

CAPS !

**Comment by pawangspandey** [comment]
Oh, thanks,
@josselyncolombet  its working now.

**Comment by alexpts** [comment]
Where I can find `access_hash` for channel?

**Comment by gino8080** [comment]
same question, I know my user.access_hash, but
how to get channel.access_hash ?

**Comment by gino8080** [comment]
> `mtproto.call('channels.inviteToChannel', { "channel": { "_": "inputChannel", //here "channel_id": "Channel ID", "access_hash": "XXXXX" }, "users":[ { "_": "inputUser", //here "user_id": "User Id", "access_hash": "XXXX" } ] })`
> 
> CAPS !

sorry i did not understood, whats the difference?

**Comment by pawangspandey** [comment]
@gino8080  @alexpts 
If you already created the channel, You may get all chats info using `messages.getAllChats` method and in the list find your channel there would be access_hash as well.

**Comment by alexpts** [comment]
I have error:
```json
{
  "_": "mt_rpc_error",
  "error_code": 400,
  "error_message": "BOT_METHOD_INVALID"
}
```

I login via bot access token:
```javascript
user = await mtproto.call('auth.importBotAuthorization', {
    bot_auth_token: "xxxxx"
});
```

**Comment by Doogiemuc** [comment]
> `mtproto.call('channels.inviteToChannel', { "channel": { "_": "inputChannel", //here "channel_id": "Channel ID", "access_hash": "XXXXX" }, "users":[ { "_": "inputUser", //here "user_id": "User Id", "access_hash": "XXXX" } ] })`
> 
> CAPS !

After correcting the caps, does this work for you?  It doesn't for me?  I get an USERS_TOO_MUCH error??? Although there are only 220 users in my channel?  Am I doing someting wrong with the above code?
