### ISSUE TITLE
How to use this library on client side? I have an issue with net module

### ISSUE THREAD

**Issue by Hellrasier** [alik0211/mtproto-core#149]

**Comment by ArenaGrenade** [comment]
@alik0211 Please look into this. There is not much documentation guiding how we should use it.

**Comment by ArenaGrenade** [comment]
@alik0211 The issue currently is the fact that there is literally no documentation on how to use the library on the browser while it is said we can do so. If a clear example code or atleast a `.md` documentation is provided, it would be better.

**Comment by alik0211** [comment]
I don't understand what the problem is. I checked the work in the browser using a webpack.
