### ISSUE TITLE
Add support NodeJS

### ISSUE THREAD

**Issue by alik0211** [alik0211/mtproto-core#15]
- [x] Storage (localStorage)
- [x] Transport (WebSocket)
- [x] navigator
- [x] crypto

## Transport API
```js
this.transport = new Transport(dcId);

this.transport.on('error', () => {});
this.transport.on('open', () => {});
this.transport.on('close', () => {});
this.transport.on('message', () => {});

this.transport.destroy();

this.transport.send();
```

**Comment by victorgoya** [comment]
By coincidence I got interested in this subject a few hours ago and started working on it. I'm not an experienced Node developer though and my first goal was to make it works on Node even if it probably breaks the browser version. But I guess it can be a starting point.

This commit sums up what I did so far https://github.com/victorgoya/mtproto-core/commit/7f35d34cd58e972642fa7105e456c8c4032a62d9

Few notes:

- I got really weird result from the FileReader polyfill (and that's why I'm bypassing it in my commit), stuff like extra bytes (always 130 and 93) at the beginning of the buffer. Maybe that's a common issue but I don't have the experience to figure it out just yet.
- I got this error `TypeError: 'set' on proxy: trap returned falsish for property 'timeOffset'` in `storage.js` so I switched all `localStorage[key] = value` to `localStorage.setItem(key, value)`
- The TextEncoder polyfill (`text-encoder-lite`) doesn't seem to behave like the browser version when undefined is passed (Chrome returns an empty Uint8Array, `text-encoder-lite` crashes), I may post a pull request later when I'm sure about what I'm doing x)

I hope this helps, thanks a lot for your work!

**Comment by Sparkenstein** [comment]
`localStorage.setItem(key, value)` Is the correct way of setting value. I think just importing a  wrapper like `node-localstorage` and assigning it to `global` should be sufficient.

something like:
```js
// storage.js
let storage;

if(typeof localStorage == "undefined"){
  global.localStorage = new LocalStorage('./db');
} else {
  storage = window.localStorage;
}

// use `storage` below everywhere
```
I haven't tested it but everything else should work for the data storing part at least

**Comment by alik0211** [comment]
Guys, thanks for the comments. Feel free to write more. I plan to release it at the end of April.

**Comment by alik0211** [comment]
Support NodeJS add in version **3.0.0-beta.2**. This version support only second DC.

Install:
```
yarn add -E @mtproto/core@beta
```

Follow the changes in the official Telegram channel: https://t.me/mtproto_core

![o9ToZfKAZSc](https://user-images.githubusercontent.com/16985862/79635888-b32da280-8184-11ea-86f0-fcbb10e2ad87.jpg)

cc @victorgoya @Sparkenstein @anhnhoktvn @manustays @Dtanguy @KonstantinKurganov

**Comment by Dtanguy** [comment]
Got this error when try to use it in node (with npm i @mtproto/core@beta) : 
`
(node:19404) UnhandledPromiseRejectionWarning: TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:708:11)
    at TCP.send (----\node_modules\@mtproto\core\src\transport\tcp\index.js:86:16)
`

Try to fix it by editing @mtproto\core\src\transport\tcp\index.js:86 to: 
`
  async send(bytes) {
    const obfuscatedBytes = await this.obfuscate(bytes);
   let testBuff = new Buffer(obfuscatedBytes);
   this.socket.write(testBuff);  
  }
`

But then it broke here :
`
(node:5540) UnhandledPromiseRejectionWarning: ReferenceError: TextEncoder is not defined
at TLSerializer.string (----\node_modules\@mtproto\core\src\tl\serializer\index.js:225:21)
at TLSerializer.predicate (----\node_modules\@mtproto\core\src\tl\serializer\index.js:117:21)
at methodData.params.forEach.paramData (----\node_modules\@mtproto\core\src\tl\serializer\index.js:98:12)
`

**Comment by alik0211** [comment]
@Dtanguy what version of Node JS do you have?

**Comment by Dtanguy** [comment]
```
node -v
v8.14.0
```

**Comment by Dtanguy** [comment]
After update (for my other DCs issue) i have retry the node version and now i got this error at every get request :

```node
(node:19324) UnhandledPromiseRejectionWarning: Error: invalid ciphertext size (must be multiple of 16 bytes)
    at ModeOfOperationIGE.decrypt (D:\Documents\GitHub\telegram_scraper\node_modules\@mtproto\core\src\utils\crypto\index.js:62:13)
    at RPC.handleEncryptedMessage (D:\Documents\GitHub\telegram_scraper\node_modules\@mtproto\core\src\rpc\index.js:339:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19324) UnhandledPromiseRejectionWarning: Error: invalid ciphertext size (must be multiple of 16 bytes)
    at ModeOfOperationIGE.decrypt (D:\Documents\GitHub\telegram_scraper\node_modules\@mtproto\core\src\utils\crypto\index.js:62:13)
    at RPC.handleEncryptedMessage (D:\Documents\GitHub\telegram_scraper\node_modules\@mtproto\core\src\rpc\index.js:339:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by theronic** [comment]
I'm also getting the "Error: invalid ciphertext size" error for all requests, even though the requests work running Node v13.11.0 locally or Node v10 on Google Cloud Functions.

**Comment by alik0211** [comment]
@Dtanguy @theronic Guys, please try to reproduce the error on nodejs **12** and @mtproto/core **3.0.0-beta.6**
. If there is an error show the code here

**Comment by dmytro-derkach** [comment]
Reproduced with NodeJS v12.16.2
Stack: 
`(node:19822) UnhandledPromiseRejectionWarning: Error: invalid ciphertext size (must be multiple of 16 bytes)
    at ModeOfOperationIGE.decrypt (/home/home/Projects/Covid-19-telegram/node_modules/@mtproto/core/src/utils/crypto/index.js:62:13)
    at RPC.handleEncryptedMessage (/home/home/Projects/Covid-19-telegram/node_modules/@mtproto/core/src/rpc/index.js:340:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19822) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19822) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Used config for production environment:
`const mtproto = new MTProto({
  api_id: API_ID,
  api_hash: API_HASH,

  test: false,
});`

if test field set to true I am getting this response:
`auth.authorization: {
  _: 'auth.authorizationSignUpRequired',
  pFlags: {},
  flags: 1,
  terms_of_service: {
    _: 'help.termsOfService',
    pFlags: {},
    flags: 0,
    id: {
      _: 'dataJSON',
      data: '{"country":"UA","min_age":false,"terms_key":"TERMS_OF_SERVICE","terms_lang":"en","terms_version":1,"terms_hash":"7dca806cb8d387c07c778ce9ef6aac04"}'
    },
    text: 'By signing up for Telegram, you agree not to:\n' +
      '\n' +
      '- Use our service to send spam or scam users.\n' +
      '- Promote violence on publicly viewable Telegram bots, groups or channels.\n' +
      '- Post pornographic content on publicly viewable Telegram bots, groups or channels.\n' +
      '\n' +
      'We reserve the right to update these Terms of Service later.',
    entities: []
  }
}`

**Comment by alik0211** [comment]
Fix in in version **3.0.0-beta.7**. Thank you very much for your help in finding the error! ❤

See more: https://t.me/mtproto_core/13

**Comment by theronic** [comment]
Pleasure, @alik0211!

**Comment by dmytro-derkach** [comment]
Will this library support local storage for nodeJS?

**Comment by alik0211** [comment]
@dmytro-derkach yes, in future releases
