### ISSUE TITLE
Support multiple users at the same time

### ISSUE THREAD

**Issue by meylisatamuradov** [alik0211/mtproto-core#150]
The idea is using only one api_id and api_hash, I would like to act as anyone who logged in using my api. Lets say '9996621111' phone signed in successfully. Now I can do any actions like sending message or getting any kind of info about '9996621111'. But When someone else logged in, let's say '9996622222', then first one is gone and all local authKey and serverSalt files overwritten. And if I want to act like first phone then I need to go through authentication again. Now What I want is any phone numbers that one time logged in successfully, store all needed authKey and serverSalt for that user, and any time to able to use the user by passing parameter(lets say phone number) to any methods. How Can I implement this?

Thanks in advance

**Comment by alik0211** [comment]
The library does not support multiple connections. Perhaps support will be added in the future. Follow the changes in the official Telegram channel - https://t.me/mtproto_core

**Comment by bigbigsir** [comment]
Does it now support multiple users？

**Comment by bigbigsir** [comment]
![image](https://user-images.githubusercontent.com/30718335/113431848-f07b5680-940e-11eb-807c-88c8fdaa114c.png)
How does this work
