### ISSUE TITLE
Request on Visibility with respect to the Upcoming Rewrite

### ISSUE THREAD

**Issue by AmanAgnihotri** [alik0211/mtproto-core#151]
I write this with respect to your following post on Telegram:

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/6022884/106423849-38b9df00-6487-11eb-9259-6b77608423f5.png">

As someone who is utilizing [mtproto-core](https://github.com/alik0211/mtproto-core) for insights in clean development of the Telegram API targeting .NET platform, I was wondering what changes you have in mind that you intend to do a rewrite of this library. Having some understanding of the changes you intend to bring to the library will be useful to me and could be useful for its users and potential contributors alike.

**Comment by alik0211** [comment]
Basically, I plan to make the following changes: improve stability, rewrite Storage, add logging, and write a lot of examples
