### ISSUE TITLE
account.registerDevice resolves to true but browser cannot receive push events

### ISSUE THREAD

**Issue by ssmlee04** [alik0211/mtproto-core#157]
Hey folks. I was able to configure my service workers and come up with a subscription token. And when I try to register my device this resolves to `true`. 

```
return mtproto.call('account.registerDevice', {
    token_type: 10,
    token,
    secret: [],
    other_uids: []
  });
```

Also I can validate that my service workers can receive push events using this website: https://web-push-codelab.glitch.me/ by providing the same token to them. 

However, I can't seem to receive any push events that's coming from Telegram. I was expecting messages coming from the telegram channels my loggedin user subscribed to. Does anyone know if there's something I can do?

**Comment by alik0211** [comment]
@ssmlee04 read this docs - https://core.telegram.org/api/push-updates

Or wait when I write guide
