### ISSUE TITLE
Current auth status

### ISSUE THREAD

**Issue by elky** [alik0211/mtproto-core#16]
Is there any way to check current auth status? I'm getting `AUTH_RESTART` error trying to log in and being already logged in. It would be good to have something like `isSignedIn: true` in MTProto object.

**Comment by alik0211** [comment]
The most reliable way I know:
```js
mtproto
  .call('users.getFullUser', {
    id: {
      _: 'inputUserSelf',
    },
  })
  .then(response => {
    // The user is logged in.
  })
  .catch(error => {
    // The user is not logged in.
  });
```
