### ISSUE TITLE
 Image reference is not in byte type

### ISSUE THREAD

**Issue by oscar-rey-mosquera** [alik0211/mtproto-core#161]
When making a request to find out the reference of your profile image, send an object with a number and it is a string of bytes
![node-js](https://user-images.githubusercontent.com/65368810/108562243-934b9b80-72cd-11eb-9dc1-a971ac796459.png)

**Comment by alik0211** [comment]
1. What version of the library do you use?
2. Just output the value to the console. What type will be there?
