### ISSUE TITLE
Incoming "updates" messages stop after first outbound API call

### ISSUE THREAD

**Issue by Shmublon** [alik0211/mtproto-core#162]
It is the same issue, like in this thread https://github.com/zerobias/telegram-mtproto/issues/53

I googled a lot but nothing helping. Exactly after first outbound API call, for example, 'messages.setTyping' or 'messages.sendMessage', it stops to send any updates.

`_mtproto.updates.on('updateShortMessage', console.log);
  _mtproto.updates.on('updatesTooLong', console.log);
  _mtproto.updates.on('updateShortChatMessage', console.log);
  _mtproto.updates.on('updateShort', console.log);
  _mtproto.updates.on('updatesCombined', console.log);
  _mtproto.updates.on('updates', console.log);
  _mtproto.updates.on('updateShortSentMessage', console.log);`

**Comment by alik0211** [comment]
I couldn't reproduce the problem. Update the library to version 6 and try again
