### ISSUE TITLE
how to download userProfilePhoto

### ISSUE THREAD

**Issue by youridol544** [alik0211/mtproto-core#163]
i want to get userProfile photo and i don’t  know how to get it

**Comment by alik0211** [comment]
@youridol544 use this docs - https://core.telegram.org/api/files

Or wait when I write guide

**Comment by aleegs** [comment]
I am using the **upload.getFile** method to download a user photo https://core.telegram.org/method/upload.getFile

ES6 example to download a user photo (for a channel/group you will need to modify some lines) 
* The _api_ object in my example is just this https://github.com/alik0211/mtproto-core/blob/master/docs/handling-common-errors.md

Get the user's info (we will need the  photo object, access_hash, id) with https://core.telegram.org/method/contacts.resolveUsername
```
const username = "user123";
const userData = await api.call("contacts.resolveUsername", { username });
const data = userData.users[0];
```
Build the  InputFileLocation parameter for the upload.getFile method
In this case we will need a inputPeerPhotoFileLocation https://core.telegram.org/constructor/inputPeerPhotoFileLocation
```
const peer = { _: "inputPeerUser", user_id: data.id, access_hash: data.access_hash };
const photoData = data.photo.photo_small; // or data.photo.photo_big

const params = {
  location: {
    _: "inputPeerPhotoFileLocation", 
    big: false,
    peer
    volume_id: photoData.volume_id,
    local_id: photoData.local_id,
  },
  limit: 512 * 512, // 1024x1024 etc
  offset: 0,
}
```

Finally get the photo bytes with upload.getFiles and our params object:
```
const response = await api.call("upload.getFile", params);
```

Example response object (https://core.telegram.org/constructor/upload.file)
``` 
response = {
  _: 'upload.file',
  type: { _: 'storage.fileJpeg' },
  mtime: 1534187223,
  bytes: Uint8Array(8376) [ ... ]
}
```
The bytes property of the response is the photo.

**Comment by alik0211** [comment]
@agsosa what lines had to be changed for the channel/group?
