### ISSUE TITLE
signIn() returns PHONE_CODE_INVALID for test phone

### ISSUE THREAD

**Issue by allandiego** [alik0211/mtproto-core#176]
**Describe the bug**
using the signIn() function from the guide https://mtproto-core.js.org allways returns status 400 PHONE_CODE_INVALID with a test phone number

**Code example**
https://gist.github.com/allandiego/fc5d6d158bd14988703793c8601fc91c

**Expected behavior**
receive the positive result from the call for auth.signIn

**Context:**
 - Os: Win10 x64
 - Library version: "@mtproto/core": "^6.0.1",
 - Node version (if node environment): node v14.16.0

**Additional context**
Im using the test: true param for MTProto instance

```ts
const phone_number = '9996624444'; // telegrams docs says to use number without +
// const phone_number = '+9996624444'; // dont know if + make difference but the guide says to use with + tried this way too  
const phone_code = '22222'; 

const { phone_code_hash} = await sendCode(phone_number) // returns the  phone_code_hash correctly

const signInResult = await signIn({ phone_code, phone_number, phone_code_hash }) // fails  400 PHONE_CODE_INVALID
```
mI doing something wrong?
https://core.telegram.org/api/auth#test-phone-numbers
docs says to use DC number associated with my user created api_id which is 2 in my case, shouldn't the verification code be 22222?

**Comment by alik0211** [comment]
Please, use "Bug report" template for issue

**Comment by allandiego** [comment]
@alik0211 I didn't know if its a bug or im doing something wrong, I have updated with the debug template

**Comment by allandiego** [comment]
So i got what was wrong, something was bothering me about the sendCode response
```
sendCode response {
  _: 'auth.sentCode',
  flags: 0,
  type: { _: 'auth.sentCodeTypeSms', length: 6 }, // < this part  length 6
  phone_code_hash: 'xxxxxxx'
}

```
The guide and telegram docs says that code should be repeated five times but in fact its 6
https://mtproto-core.js.org/docs/test-phone-numbers#format

https://core.telegram.org/api/auth#test-phone-numbers
A user like this would always get XXXXX as the login confirmation code (the DC number, repeated five times)

**Comment by yashwanth2804** [comment]
Is your issue resolved ? I am getting the same problem, whatever I give, its always `PHONE_CODE_INVALID`

**Comment by smff** [comment]
any ideas?
