### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/inflate.js' is not defined by "exports" in /node_modules/pako/package.json

### ISSUE THREAD

**Issue by AhabweEmmanuel** [alik0211/mtproto-core#178]
This can be fixed by modifying  @mtproto/core/src/tl/deserializer/index.js:

remove --> import { inflate } from 'pako/lib/inflate.js';

replace with --> import { inflate } from 'pako';

**Comment by alik0211** [comment]
Please fill out the issue using the "Bug report" template

**Comment by ace-wolf** [comment]
Same error for me

**Comment by ebinxavier** [comment]
Same for me also

**Comment by nnmtesuji** [comment]
Do anyone can resolve this problem?

**Comment by nnmtesuji** [comment]
I found it
This can be fixed by modifying @mtproto/core/src/tl/deserializer/index.js:

import { inflate } from 'pako/lib/inflate.js'; -> const { inflate } = require('pako');

**Comment by alik0211** [comment]
Fixed in version 6.1.1 - https://t.me/mtproto_core/32
