### ISSUE TITLE
"upload.getFile" not working

### ISSUE THREAD

**Issue by malufett** [alik0211/mtproto-core#179]
Describe the bug
Cannot make the "upload.getFile" to work the request is rejected. I use the Location object sent by the "auth.signIn" or "users.getFullUser" and none of them works. Anyone does make it works and what is the proper parameters?

Code example
![image](https://user-images.githubusercontent.com/3251821/115460528-5c730280-a1f6-11eb-9d31-dd1486232187.png)

Expected behavior
it should able to response based on https://core.telegram.org/type/upload.File

Screenshots
![image](https://user-images.githubusercontent.com/3251821/115460358-2c2b6400-a1f6-11eb-9e64-1e8d9b76de33.png)

Context:

Library environment: node
Library version: 6.0.1
Node version (if node environment): 12.20.1
Additional context

**Comment by pogudin-sergey** [comment]
> For profile pictures of users, channels, supergroups and groups, since in most occasions they are encountered as simple fileLocationToBeDeprecated constructors without an associated photo, inputPeerPhotoFileLocation has to be used...

See: https://core.telegram.org/api/files

**Comment by malufett** [comment]
> Invalid location param.
> 
> > For profile pictures of users, channels, supergroups and groups, since in most occasions they are encountered as simple fileLocationToBeDeprecated constructors without an associated photo, inputPeerPhotoFileLocation has to be used...
> 
> See: https://core.telegram.org/api/files

yep it is..do you have sample of working location params?

**Comment by pogudin-sergey** [comment]
> yep it is..do you have sample of working location params?

```js
location = {
          _: 'inputDocumentFileLocation',
          id: m.media.document.id,
          access_hash: m.media.document.access_hash,
          file_reference: m.media.document.file_reference,
        };
```
```js
location = {
          _: 'inputPhotoFileLocation',
          id: m.media.photo.id,
          access_hash: m.media.photo.access_hash,
          file_reference: m.media.photo.file_reference,
          thumb_size: getSizeType(m.media.photo.sizes),
        };
```

**Comment by malufett** [comment]
> > yep it is..do you have sample of working location params?
> 
> ```js
> location = {
>           _: 'inputDocumentFileLocation',
>           id: m.media.document.id,
>           access_hash: m.media.document.access_hash,
>           file_reference: m.media.document.file_reference,
>         };
> ```
> 
> ```js
> location = {
>           _: 'inputPhotoFileLocation',
>           id: m.media.photo.id,
>           access_hash: m.media.photo.access_hash,
>           file_reference: m.media.photo.file_reference,
>           thumb_size: getSizeType(m.media.photo.sizes),
>         };
> ```

hi, where does the access_hash located or generated? I have check the response from other responses(like userProfilePhoto and etc) api and none of them has that access_hash.. Thanks

**Comment by pogudin-sergey** [comment]
> hi, where does the access_hash located or generated? I have check the response from other responses(like userProfilePhoto and etc) api and none of them has that access_hash.. Thanks

access_hash is have on incoming message, user profiles.

**Comment by malufett** [comment]
this is the sample of the data I'm getting.,..
![image](https://user-images.githubusercontent.com/3251821/115724918-60666800-a34f-11eb-9662-1cb9e6919d9b.png)
