### ISSUE TITLE
Improve working with different DC

### ISSUE THREAD

**Issue by alik0211** [alik0211/mtproto-core#18]

**Comment by Dtanguy** [comment]
I am trying to "upload.getFile" on media, sometime they are in differents Dc than mine, so i got the error "FILE_MIGRATE_X" (X is ne Dc number where the file is).

I have try to switch Dc with "mtproto.changeDc(X);" but then i can auth with error "PHONE_MIGRATE_4" (4 is my home Dc, the one i am connected by default).

After some documentation reading, i have try to export my current auth from Dc 4 to Dc X this way :
`exportAuth(nb) {
    this.mtproto
      .call("auth.exportAuthorization", {
        dc_id: nb,
      })
      .then((res) => {
        console.log(res);
        this.mtproto.changeDc(nb);
        this.mtproto
          .call("auth.importAuthorization", {
            id: res.id,
            bytes: res.bytes,
          })
          .then((res) => {
            console.log(res);
          })
          .catch((error) => {
            console.log(error);
          });
      })
      .catch((error) => {
        console.log(error);
      });
  }`

It kinda work, the auth.import succed and i am set as connected to the new Dc (in my case Dc 1), but now when i try to "upload.getfile" i got an "USER_MIGRATE_4" error.

I am stuck at this point, do you have any advice ?

**Comment by Dtanguy** [comment]
Got "AUTH_KEY_UNREGISTERED" when trying to log, but it kinda work (can get chats, message etc..) But cannot "upload.getFile" on different DC, it return also "AUTH_KEY_UNREGISTERED"

Sign in: 
```
this.mtproto
      .call(
        "auth.signIn",
        {
          phone_code: code,
          phone_number: this.config.telegram.phone,
          phone_code_hash: this.phone_code_hash,
        },
        { dcId: 4, syncAuth: true }
      )
      .then((result) => {
        console.log(`auth.signIn[result]:`, result);
      })
      .catch((error) => {
        console.log("error");
        console.error(error);
      });
```

Get File: 
```
call = {
    //precise: false,
    location: loc,
    offset: 0,
    limit: 1024 * 1024,
};
  
this.mtproto
	.call(
		"upload.getFile",
        call,       
        { dcId: location.dc_id }
	)
	.then((result) => {
		console.log(result
	})
	.catch((error) => {      
		console.error(error);
	});
```

**Comment by alik0211** [comment]
@Dtanguy
1. Auth to default DC with `syncAuth`
```js
mtproto.call('auth.signIn', params, { syncAuth: true });
```
2. After you may use any DC 🙃
```js
mtproto.call('upload.getFile', params, { dcId: 4 });
```

Note about [`upload.getFile`](https://core.telegram.org/method/upload.getFile): if you have an [`fileLocationToBeDeprecated`](https://core.telegram.org/constructor/fileLocationToBeDeprecated), you need to use an [`inputPeerPhotoFileLocation`](https://core.telegram.org/constructor/inputPeerPhotoFileLocation)
More detailed: https://core.telegram.org/api/files#downloading-files

**Comment by Dtanguy** [comment]
if i request phone code (auth.sendCode) with the default DC, got "PHONE_MIGRATE_4" error.
If i request code with DC 4 and then auth.signIn with the default DC i got "PHONE_CODE_EXPIRED"

**Comment by alik0211** [comment]
@Dtanguy fix in version **3.0.0-beta.4**. Install:
```
yarn add -E @mtproto/core@beta
```

This should work:
```js
mtproto
  .call('auth.sendCode', params, { dcId: 4 })
  .then(result => {
    return mtproto
      .call('auth.signIn', params, { dcId: 4, syncAuth: true })
      .then(result => {
        console.log('auth.signIn[result]:', result);
        // You are auth in to all DC's
      });
  })
  .catch(error => {
    console.error(error);
  });
```

In future versions, I will add the option to change the default DC.

**Comment by Dtanguy** [comment]
@alik0211 

Got "AUTH_KEY_UNREGISTERED" error when
```
 call('auth.signIn', params, { dcId: 4, syncAuth: true })
```

**Comment by alik0211** [comment]
@Dtanguy you use browser or nodejs? What version mtproto-core do you use? Please add full code with comments

**Comment by Dtanguy** [comment]
```node
  "dependencies": {
    "@mtproto/core": "^3.0.0-beta.4"
  },
```

Browser for the moment, i will use nodejs on a second time, but debug is easyer with a small web page as interface.

```node
 requestCode() {
    this.mtproto
      .call(
        "auth.sendCode",
        {
          phone_number: this.config.telegram.phone,
          api_id: this.config.telegram.id,
          api_hash: this.config.telegram.hash,
          settings: {
            _: "codeSettings",
          },
        },
        {
          dcId: this.config.telegram.dcId, // = 4
        }
      )
      .then((result) => {
        this.phone_code_hash = result.phone_code_hash;
        console.log(result.phone_code_hash);
      })
      .catch((err) => {
        console.error(err);
      });
  }

  verifyCode(code) {
    let params = {
      phone_code: code,
      phone_number: this.config.telegram.phone,
      phone_code_hash: this.phone_code_hash,
    };
    console.log(params);
    this.mtproto
      .call("auth.signIn", params, {
        dcId: this.config.telegram.dcId, // = 4
        syncAuth: true,
      })
      .then((result) => {
        console.log("auth.signIn[result]:", result);
      })
      .catch((err) => {
        console.error(err);
      });
  }

getMedia(params, dc_id, callback) {
    this.mtproto
      .call("upload.getFile", params, { dcId: dc_id }) // dc_id is the dc of the selected file
      .then((result) => {
        console.log(result);
      })
      .catch((err) => {
        console.error(err);
      });
}
```

This 3 functions are triger by a small web page for allow me to enter the phone code:
![image](https://user-images.githubusercontent.com/10078093/79980216-0ebca080-84a3-11ea-89e3-e1ad1f13c8da.png)

**Comment by alik0211** [comment]
@Dtanguy if you use browser, try run `localStorage.clear()` and repeat auth

**Comment by Dtanguy** [comment]
Good catch. I works on the browser version, thanks :)

**Comment by marswong** [comment]
@alik0211 auth.signIn always get `PHONE_CODE_EXPIRED` error now
