### ISSUE TITLE
Transport error: { type: 'socket' }

### ISSUE THREAD

**Issue by reflash** [alik0211/mtproto-core#200]
**Describe the bug**
Running with 5.3.0 version - getting the error:
```
Transport error: { type: 'socket' }
```

This code has worked previously, so not sure what's the issue now

**Code example**
```typescript
await this.mtProtoClient.call('auth.importBotAuthorization', {
    bot_auth_token: token,
})
```

**Expected behavior**
Call is finished successfully

**Context:**
 - Library version: 5.3.0
 - Node version (if node environment): 12.22.1

**Comment by joeberetta** [comment]
@reflash do you have any progress with it? Some time ago tried to use it for PoW and got same error, but hadn't time to check where's the real problem

**Comment by reflash** [comment]
> @reflash do you have any progress with it? Some time ago tried to use it for PoW and got same error, but hadn't time to check where's the real problem

I think I haven't found any solution to that and I can't really reproduce the same condition atm
