### ISSUE TITLE
Parsing html or markup in message.sendMessage not working

### ISSUE THREAD

**Issue by meth0xy** [alik0211/mtproto-core#216]
**Describe the bug**
I am trying to send a message with styled format, unfortuntley nothing seems to work, the messages are all send as a string only

**Code example**
```
api.call("messages.sendMessage", {
    clear_draft: true,
    parse_mode: "html",
    peer: {
      _: "inputPeerSelf",
    },
    message: "<b>Test</b>",
    entities: [
      {
        _: "messageEntityBold",
        offset: 6,
        length: 13,
      },
    ],

    random_id:
      Math.ceil(Math.random() * 0xffffff) + Math.ceil(Math.random() * 0xffffff),
  });
```

**Expected behavior**
A Message with a bold text.

**Context:**
 - Library environment: node 14.7
 - Library version:  "@mtproto/core": "6.0.1",

**Additional context**
Same happens when i use `parse_mode: "markup"`.

**Comment by meth0xy** [comment]
Okay i found out that i have to use the MessageEnitys and specify each word with an entity.

**Comment by VityaSchel** [comment]
> Okay i found out that i have to use the MessageEnitys and specify each word with an entity.

Could you share an example of code?

**Comment by meth0xy** [comment]
> > Okay i found out that i have to use the MessageEnitys and specify each word with an entity.
> 
> Could you share an example of code?

`api.call('messages.sendMessage', {
  clear_draft: true,

  peer: {
    _: 'inputPeerSelf',
  },
  message: 'Hello @mtproto_core',
  entities: [
    {
      _: 'messageEntityBold',
      offset: 6,
      length: 13,
    },
  ],

  random_id: Math.ceil(Math.random() * 0xffffff) + Math.ceil(Math.random() * 0xffffff),
});`

So the entities Array `entities: [
    {
      _: 'messageEntityBold',
      offset: 6,
      length: 13,
    },
  ],` is for the formatting you can add a second object in that array for example messageEntityCode and set the offset to the specific letter in your message and the length of the word.
Here are all possible message entities 
https://core.telegram.org/type/MessageEntity
