### ISSUE TITLE
Error "UDPATE_APP_TO_LOGIN"

### ISSUE THREAD

**Issue by superhipz** [alik0211/mtproto-core#218]
I meet the error "UPDATE_APP_TO_LOGIN" when try to login through API. Is this an library error or telegram had new update so library cannot handle

**Comment by jayserjune** [comment]
I also encountered the same problem, and there is no official explanation。

**Comment by superhipz** [comment]
Yeah let's wait for creator to fix this

**Comment by pogudin-sergey** [comment]
I also encountered the same problem on getCode

**Comment by arthot** [comment]
According to Telegram, 
> Telegram has started enforcing the use of 64-bit identifiers for users and chats, and the current stable version of the library does not support them yet. If you try to login, you may see UPDATE_APP_TO_LOGIN error.

It means this library must implement support of [131 layer](https://core.telegram.org/api/layers#layer-133) (current is 121)

**Comment by kamil996** [comment]
Fingers crossed for fast fix by @alik0211. Youre the man!

**Comment by superhipz** [comment]
Wow i fixed this by change the layer from 121 to 133. Thank you so much @alik0211

**Comment by ember999** [comment]
> Wow i fixed this by change the layer from 121 to 133. Thank you so much @alik0211

How to do？

**Comment by hudijani** [comment]
![image](https://user-images.githubusercontent.com/33799302/144275148-0409658b-a968-42cb-baea-3eba3e5bb7b4.png)

**Comment by pogudin-sergey** [comment]
And replace /scheme/api.json new version from https://core.telegram.org/api/layers#layer-133

**Comment by pogudin-sergey** [comment]
Repeat after me https://github.com/pogudin-sergey/mtproto-core/commit/e4a563ac83e50c233efd4c6eb315e218009cbe9f

**Comment by OwnageeeeeeDima** [comment]
Changing the layer from 121 to 133 or 131 did not help, the following error occurs
Not found predicate with id: 3600285445
(node:12564) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_' of undefined
    at RPC.handleDecryptedMessage (E:\projects\work\node\freestuff\node_modules\@mtproto\core\src\rpc\index.js:549:26)
    at RPC.handleEncryptedMessage (E:\projects\work\node\freestuff\node_modules\@mtproto\core\src\rpc\index.js:451:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by tuannfq** [comment]
> Changing the layer from 121 to 133 or 131 did not help, the following error occurs Not found predicate with id: 3600285445 (node:12564) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_' of undefined at RPC.handleDecryptedMessage (E:\projects\work\node\freestuff\node_modules@mtproto\core\src\rpc\index.js:549:26) at RPC.handleEncryptedMessage (E:\projects\work\node\freestuff\node_modules@mtproto\core\src\rpc\index.js:451:10) at processTicksAndRejections (internal/process/task_queues.js:95:5)

you also need change json file in /scheme/api.json. Quickly you can add dependecy from this repo https://github.com/pogudin-sergey/mtproto-core

**Comment by superhipz** [comment]
I dont have Scheme folder so i create it and copy paste api.json file and it still works. Thank you @tuannfq

**Comment by superhipz** [comment]
> yeah, why was this closed without a PR ?

Sorry this is my first time using git to open an issue

**Comment by ember999** [comment]
![image](https://user-images.githubusercontent.com/71760826/144358475-3b610745-7c7e-45ce-b315-cd5840d4906c.png)

I tried the above solution, but there was still no solution

**Comment by pogudin-sergey** [comment]
PR for update layer & fix this problem: https://github.com/alik0211/mtproto-core/pull/219

**Comment by alik0211** [comment]
Fixed in version 6.1.0 - https://t.me/mtproto_core/31
