### ISSUE TITLE
Handling multiple users in the backend - Question

### ISSUE THREAD

**Issue by TheRyan1** [alik0211/mtproto-core#222]
When init MTproto in the backend, the session information used is for a single user.
Is there a way that multiple users would be able to use a single instance? Or would each user need a new instance with their own session data?

What I want to do: 
Login from the front end and call the methods from the backend

**Context:**
 - Library environment: node 
 - Library version: 6.1.0
 - Node version (if node environment): latest

**Comment by refaldyrk** [comment]
how this close, i have same question

**Comment by refaldyrk** [comment]
what a answer for this question, i need pls

**Comment by TheRyan1** [comment]
> how this close, i have same question

User's logged in with an email and password. Then connected their account using their phone number. Once authenticated, I stored the session generated by auth.signIn method into the db. So each time they made a call to the mtproto methods, it would use the stored session.

```javascript
  try {
        const { session } = await User.findById(req.id);
        const parsedSession = JSON.parse(session);
        if (Object.keys(parsedSession).length > 3) {
          let tempStorage = new Storage();
          for (let [key, value] of Object.entries(parsedSession)) {
            tempStorage.set(key, value);
          }
          const _MTproto = new MTprotoAPI(tempStorage);
          const user = await _MTproto.getUser();
          if (user.user) {
            res.send({ user: user.user, step: "dashboard" });
          } else {
            res.send("An error occured");
          }
        } else {
          res.send({ message: "Sign in required", step: "enterPhone" });
        }
      } catch (err) {
        console.log(err);
      }
```
