### ISSUE TITLE
Update events with "Restrict content saving"

### ISSUE THREAD

**Issue by Sated** [alik0211/mtproto-core#236]
Update events are not processed when sending messages to groups with the "Restrict content saving" option enabled. "message" field is empty and media marked "not supported"

![image](https://user-images.githubusercontent.com/66825082/149669131-dbf4252f-910e-4389-a128-5c8c44b1684c.png)
![image](https://user-images.githubusercontent.com/66825082/149669201-40febd7f-2c25-460a-bd29-167eac889ce5.png)

**Comment by alexsanderluisdev** [comment]
I'm having this error too. Any suggestion?

**Comment by alexsanderluisdev** [comment]
@alik0211 do you have any fixes for this bug?

**Comment by alik0211** [comment]
The layer has been updated to 139 in version 6.2.0. Please check if everything is working fine now?
