### ISSUE TITLE
Channels with a ban on copying, does not read, displays messages

### ISSUE THREAD

**Issue by AndreyZvz** [alik0211/mtproto-core#244]
![image](https://user-images.githubusercontent.com/27228127/158886425-9b7a15e9-a851-4ca2-a262-47a4185ca234.png)

When receiving messages in channels where the ability to copy and forward messages is limited, the api cannot display the message and displays a message about the need to update the application

**Comment by alik0211** [comment]
The layer has been updated to 139 in version 6.2.0.
