### ISSUE TITLE
Add support multiple accounts

### ISSUE THREAD

**Issue by alik0211** [alik0211/mtproto-core#25]

**Comment by acerbisgianluca** [comment]
Hi, I've a question. Can I get the user authorization token and re-login without asking him his verification code? I'm trying to create an Alexa skill, so for every request I've to connect to Telegram servers using a different user, but the same client

**Comment by alik0211** [comment]
@acerbisgianluca Saving authorization does not work for nodejs. I will fix this in future releases

**Comment by alik0211** [comment]
@acerbisgianluca Add localStorage for nodejs in version **3.1.0**. More: https://t.me/mtproto_core/16

**Comment by velsa** [comment]
Can you please give an example on how to identify that there's a saved authorization for the user and how to use it instead of sign in?

**Comment by alik0211** [comment]
@velsa https://github.com/alik0211/mtproto-core/issues/16#issuecomment-609359855

**Comment by zzdhidden** [comment]
I wan't save auth info in other db. can you please provide a custom async store like this:

`new MTProto({ store: { set(k, v){}, get(k){} })`

**Comment by alik0211** [comment]
@zzdhidden https://github.com/alik0211/mtproto-core#customlocalstorage-localstorage
