### ISSUE TITLE
localStorage is not defined when run this code

### ISSUE THREAD

**Issue by LayNath242** [alik0211/mtproto-core#26]
const { MTProto } = require('@mtproto/core');
 
const api_id = 'xxxxx';
const api_hash = 'xxxxxxxx';
 
// 1. Create an instance
const mtproto = new MTProto({
  api_id,
  api_hash,
  test: true,
});

**Comment by alik0211** [comment]
You are probably running the code in NodeJS. Version 2.0.2 does not support NodeJS

Now you can use the beta version:
```js
yarn add -E @mtproto/core@beta
```

Follow the updates in the Telegram channel: https://t.me/mtproto_core/6

**Comment by LayNath242** [comment]
It work now thank you. Can we custom storage
