### ISSUE TITLE
How to return value 

### ISSUE THREAD

**Issue by LayNath242** [alik0211/mtproto-core#27]
I`m new in node js and I don`t how to return value from mtproto.

const mtproto = new MTProto({
    api_id,
    api_hash,

    // Use test servers
    test: true,
});

const getCountry = async () => {
    mtproto.call('help.getNearestDc').then((result) => {
        return result.country;
    });
};

const country = getCountry();
console.log(country);

when I run it return Error
Error: invalid ciphertext size (must be multiple of 16 bytes)

**Comment by alik0211** [comment]
This is not related to mtproto-core. See: https://dev.to/hardy613/asynchronous-vs-synchronous-programming-23ed

You might need something like this:
```js
(async () => {
  const { country } = await mtproto.call('help.getNearestDc');

  console.log(`country:`, country);
})();
```
