### ISSUE TITLE
Handle all MIGRATE errors

### ISSUE THREAD

**Issue by alik0211** [alik0211/mtproto-core#3]

**Comment by VityaSchel** [comment]
<img src="https://user-images.githubusercontent.com/59040542/193450726-a0b4e442-6f38-480c-a00a-fedaab9de263.gif" width="100%" />

**Comment by VityaSchel** [comment]
{"_": "mt_rpc_error", "error_code": 303, "error_message": "PHONE_MIGRATE_1"}

`+999661000`
