### ISSUE TITLE
Login without confirmation (not first time)

### ISSUE THREAD

**Issue by IIE4EHbKAKOKC** [alik0211/mtproto-core#30]
I need to be able to log in once, and then logging in automatically (without receiving SMS or another confirmations). Is it possible?
Use is planned in Electron application

**Comment by alik0211** [comment]
Yes. If you use the browser, the authorization is automatically saved in localStorage.

This doesn't work in Node JS right now. I will fix this in future releases. Keep an eye on it in the Telegram channel: https://t.me/mtproto_core
