### ISSUE TITLE
How to correctly destror api instance?

### ISSUE THREAD

**Issue by zdm** [alik0211/mtproto-core#300]
Hi,
After api instance created - process is not excited, because event loop is not free,
I thik api keeos persistent connection to the telegram servers.
So, how to correctly desroy the api anf unload it from the memory?

**Comment by zdm** [comment]
Hey,
I found this it sreates persistent socket.
Is it possible to add `destroy` methis to destroy rpc clients and destroy opened sockets?.

**Comment by fedyk** [comment]
I did attempt to add the destroy method here https://github.com/alik0211/mtproto-core/pull/235/files. Works fine on fork.

**Comment by zdm** [comment]
yes, thank you
i am alo using the path
but it is better to have this functionality in the core

**Comment by zdm** [comment]
Seems that this project is not welll-supported, no sense to keep issues open
