### ISSUE TITLE
when i am printing the user variable it does not have value 

### ISSUE THREAD

**Issue by somgupta13** [alik0211/mtproto-core#37]
``const { MTProto, getSRPParams } = require('@mtproto/core');
const prompt = require('prompt');

const mtproto = new MTProto({
  api_id: 1056862,
  api_hash: '85b72864f343b7346733c84720193a27',

  test: false,
});

const phone = '+918085603914';
const code = '2222';
// const password = 'hellojs';

function sendCode(phone) {
	// console.log("hello");
  return mtproto.call('auth.sendCode', {
	  api_id: 1056862,
  api_hash: '85b72864f343b7346733c84720193a27',
    phone_number: phone,
    settings: {
      _: 'codeSettings',
    },
  })
	  // .catch(error=>{console.log(error)});
}

sendCode(phone)
  .catch(error => {
    if (error.error_message.includes('_MIGRATE_')) {
      const [type, nextDcId] = error.error_message.split('_MIGRATE_');

      mtproto.setDefaultDc(+nextDcId);

      return sendCode(phone);
    }
  })
  .then(  result => {
	f1(result.phone_code_hash);
	
  })
  

async function f1(phone_code_hash){
	prompt.start();
	await prompt.get(['username'], async function (err, result) {
    if (err) { console.log(err); }
		else{
			// console.log(phone,phone_code_hash,result.username);
			// console.log(typeof(result.username));
			
	 		const { user } = await mtproto.call('auth.signIn', {
    			phone_number   : phone,
    			phone_code_hash: phone_code_hash,
    			phone_code     : result.username
  			}).catch(function(err){console.log(err);});
			console.log("hi"+user);
		
	 }
	});
}

**Comment by flaviolacer** [comment]
"Username" only shows if you have defined on your telegram user. You can find in the result.user.username. ex:

client.call('auth.signIn', {
        phone_number: state.phone_number,
        phone_code_hash: state.phone_code_hash,
        phone_code: state.code
    }).then(result => {
        console.log("Logged:", result.user.username);
        return result;
    }).catch(error => {
        console.log(error);
        process.exit();
    });

There you can get user.first_name and user.last_name too.

**Comment by somgupta13** [comment]
My user object is empty while i am printing it?how can i resolve this
