### ISSUE TITLE
Is there any way to keep signed?

### ISSUE THREAD

**Issue by flaviolacer** [alik0211/mtproto-core#38]
i'm searching for a storage to avoid signin all the time.

**Comment by somgupta13** [comment]
how have u created the client can u show the code

**Comment by flaviolacer** [comment]
No problem.

let state = {
        phone_number:'XXXXXXXXXXXXXX', // basically it is your phone number
 };

let sendcodeParams = {
        phone_number: state.phone_number,
        type: {_: 'auth.sentCodeTypeApp'}, // send to app besides SMS
        settings: {
            _: 'codeSettings',
        }
    };

    await client.call('auth.sendCode', sendcodeParams).then(result => {
        console.log("Send code response:", result);
        state.phone_code_hash = result.phone_code_hash;

        return result;
    }).catch(error => {
        if (error.error_message.includes('_MIGRATE_')) {
            const [type, nextDcId] = error.error_message.split('_MIGRATE_');

            client.setDefaultDc(+nextDcId);
            return connect();
        } else {
            console.log(error);
            process.exit();
        }
    });

**Comment by somgupta13** [comment]
actually i also sigin various times so i m also facing same issue

**Comment by somgupta13** [comment]
i have found some function which can help us in that i am implentating those
[1.link1](https://core.telegram.org/method/auth.exportAuthorization)
[2.link2](https://core.telegram.org/method/auth.importAuthorization)

**Comment by somgupta13** [comment]
can you help me with a issue sometimes it return the signin object  sometimes not whats the issue

**Comment by somgupta13** [comment]
hey can we connect on telegram 
https://t.me/SomGupta

**Comment by alik0211** [comment]
@flaviolacer I will add this feature in the next few days. Watch it in the channel - https://t.me/mtproto_core

**Comment by flaviolacer** [comment]
Thanks @alik0211! Recetly i had an FLOOD_WAIT_X. I Think that happened because i had lots of sigins.

**Comment by flaviolacer** [comment]
> can you help me with a issue sometimes it return the signin object sometimes not whats the issue

I think you have to open an issue just for that. Regards!
