### ISSUE TITLE
error user-migrate-5 auth-key-unregistered 

### ISSUE THREAD

**Issue by YusraZaidi** [alik0211/mtproto-core#42]
i get these errors on using messages.sendMessage() 
i was trying to maintain external file to store result id & byte array. 
so how to set the same data center

**Comment by alik0211** [comment]
@YusraZaidi 
1. What version of the library do you use?
2. Show your code
3. Show all errors

**Comment by YusraZaidi** [comment]
npm version : 6.14.4
@mtproto/core 3.0.1
code of file1


`const { MTProto } = require('@mtproto/core');
const prompt = require('prompt');
const fs = require('fs');
const yaml = require('js-yaml');
var data={};
const mtproto = new MTProto({
api_id:xxx,
api_hash:'bxxx88',

test: false,
});
//done
const phone = '+9xx22';
const code = '2222';
// const password = 'hellojs';

function sendCode(phone) {
	console.log("hello");
	return mtproto.call('auth.sendCode', {
		api_id:xx, 
		api_hash:'b58xcxxx88',
		phone_number: phone,
		settings: {
			_: 'codeSettings',
		},
	})
	 .catch(error=>{console.log("err 6"+error)});
}

sendCode(phone)
.catch(error => {
	console.log("err 1 "+error);
	if (error.error_message.includes('_MIGRATE_')) {
    	  const [type, nextDcId] = error.error_message.split('_MIGRATE_');
			mtproto.setDefaultDc(+nextDcId);
			return sendCode(phone).catch(error=>{console.log("err 2 "+error)});;
	}	
})
.then( result => {
	f1(result.phone_code_hash);
});

async function f1(phone_code_hash){
	prompt.start();
	await prompt.get(['username'], async function (err, result) {
		if (err) { console.log(err); }
		else{
			const { user } = await mtproto.call('auth.signIn', {
				phone_number   : phone,
				phone_code_hash: phone_code_hash,
				phone_code     : result.username
			},{dcId:5,syncAuth:false}).then(result => {
				console.log("Logged:", result);
				mtproto.call('help.getConfig').then(result=>{console.log("ans ",result.this_dc,"   ",result.dc_options);});
					mtproto.call('auth.exportAuthorization',{dc_id: 5},)
					.catch(err=>{
						console.log("err 5"+err);
					})
					return result;
					}).catch(error => {
						console.log(error);
						process.exit();
					});
				}
	});
}

`

//////////////
code of file 2
///////////

`const { MTProto } = require('@mtproto/core');
const fs = require('fs')
var data=[];
const mtproto = new MTProto({
	api_id:1xxx
	api_hash:'b583xxxx',
	test: false,
});

async function fileread(){
	await fs.readFile('test', 'utf-8', async (err, data1) => {
    if(err) {
        throw err;
    }
	var x=await JSON.parse(data1);
	var data3=[];
	 for (var key in x) {
		if (x.hasOwnProperty(key)) {
			var val =  x[key];
			await data3.push(val);
		}
	}
	data=await Uint8Array.from(data3);
	sendcode()
});

}
async function sendcode(){
	await mtproto.call('auth.importAuthorization',{id:127xx,bytes:data},{syncAuth:false})
	.then(result=>{
		console.log("Logged1:", result);
		message().then(result=>{console.log(result);}).catch(error=>{
			console.log(error);
			if (error.error_message.includes('_MIGRATE_')) {
				const [type, nextDcId] = error.error_message.split('_MIGRATE_');
				mtproto.setDefaultDc(+nextDcId);
				message().catch(err=>{console.log(err)})
				}
		});
	}).catch(err=>{console.log(err);
 	});
	
}

async function message(){
	return mtproto.call('messages.sendMessage',{
			peer:{
				_ :'inputPeerUser',
				user_id:10xx2,
				access_hash:0							 
			},
			message:"hiii",
			random_id:6788
	})
}
fileread()				
`

**Comment by YusraZaidi** [comment]
as i am accessing 5 th dc so it dont have the key for that and when is set to syncAuth:true the command prompt holds so how to get the id and bytes of dc 5

**Comment by alik0211** [comment]
@YusraZaidi you don't have to worry about saving your authorization anymore. This feature add in version **3.1.0**. More detailed: https://t.me/mtproto_core/16

**Comment by YusraZaidi** [comment]
thank you
