### ISSUE TITLE
Global error event

### ISSUE THREAD

**Issue by flaviolacer** [alik0211/mtproto-core#46]
Is there anyway to get globals connection errors events? Sometimes i get "transport error". I Revoked a session an i got "SESSION_REVOKED" from methods. Global event handling for connection problems will help with this issues.

**Comment by alik0211** [comment]
I have no idea how to handle transport errors (I'll deal with it later).

For API you can create a global error handler yourself. Pseudocode:
```js
const { MTProto } = require('@mtproto/core');

const _mtproto = new MTProto({
  api_id: 'YOU_API_ID',
  api_hash: 'YOU_API_HASH',
});

const mtproto = {
  call(method, params = {}, options = {}) {
    return _mtproto.call(method, (params = {}), (options = {})).catch(error => {
      if (error.error_message === 'SESSION_REVOKED') {
        // Handle SESSION_REVOKED
      }

      return Promise.reject(error);
    });
  },
};
```

**Comment by flaviolacer** [comment]
Overriding a method is not the best practice because you are considering that we will use just one method. But, ok for now. Thanks!
