### ISSUE TITLE
more methods to save session

### ISSUE THREAD

**Issue by Sparkenstein** [alik0211/mtproto-core#47]
## Issue
Both node and browser environments can save sessions in their localstorage as of now, which may work fine for general use cases. but if user is on temporary device like Heroku or even Electron, the current storage will not work, and will get destroyed on each restart. 

One alternative I can suggest is using "String Session" like [telethon](https://github.com/LonamiWebs/Telethon/blob/master/telethon/sessions/string.py) does in python. it's basically emitting a string that contains our sessions information which user can store anywhere he want, and when he wants to log back in, he just provides that string to session manager and lib restarts the session. 

I believe there are other ways to tackle this as well, it's generally a good idea to let user decide where he wants to store his data.

**Comment by alik0211** [comment]
Good issue! I will add this in future releases.

**Comment by deblanco** [comment]
!!

Looking after this issue, I really need it

**Comment by alik0211** [comment]
This feature is coming out soon! Subscribe to the Telegram channel —  [@mtproto_core](https://t.me/mtproto_core).

**Comment by alik0211** [comment]
Add in version 3.2.0. More information about the new version — https://t.me/mtproto_core/18
