### ISSUE TITLE
Send multiple files (images) to self/any user

### ISSUE THREAD

**Issue by FrixaCoder** [alik0211/mtproto-core#49]
Can't figure out how to configure `mtproto.call("messages.sendMessage/messages.sendMedia")`, `params` or `options` to send multiple images to myself. Is there any example?

**Comment by alik0211** [comment]
There is no example now, I will add it sometime (watch out for in [@mtproto_core](https://t.me/mtproto_core)). It can help you - https://core.telegram.org/api/files

**Comment by bigbigsir** [comment]
Do you have a solution? I don't know how to send picture messages
