### ISSUE TITLE
Error after using some time

### ISSUE THREAD

**Issue by flaviolacer** [alik0211/mtproto-core#50]
I don't know how to generate, but i'm getting this error after working sometime:
/app/telegram it´s my local application path.

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
5|telegram  | Error: bad_server_salt. Not found message with id 6827092132166629724
5|telegram  |     at RPC.handleDecryptedMessage (/app/telegram/node_modules/@mtproto/core/src/rpc/index.cjs:376:17)
5|telegram  |     at RPC.handleEncryptedMessage (/app/telegram/node_modules/@mtproto/core/src/rpc/index.cjs:351:10)
5|telegram  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by alik0211** [comment]
How much time, approximately, passed before the error?

**Comment by yurifontoura** [comment]
That looks same to me. The API works fine before the error. And after some time (I dont know exactly how much, between night and next morning) it says:

>(node:5083) UnhandledPromiseRejectionWarning: Error: bad_server_salt. Not found message with id 6829681089794461524
    at RPC.handleDecryptedMessage (/home/ubuntu/node_modules/@mtproto/core/src/rpc/index.cjs:376:17)
    at RPC.handleEncryptedMessage (/home/ubuntu/node_modules/@mtproto/core/src/rpc/index.cjs:351:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 161)
>

Im searching the problem reason, and nothing relevant at now. Bytheway I... 
```
mtproto.call('auth.signIn', {
    phone_number,
    phone_code_hash,
    phone_code,

})
```

... just once start. Is necessary to periodically call it with new phone code and hash while running?

**Comment by flaviolacer** [comment]
Exactly! I trying to discover a pattern, but i couldn't find. After some time, stop to receive the updates too. I think that may be is related.

**Comment by alik0211** [comment]
What is the "some time" equal to?

**Comment by yurifontoura** [comment]
Im watching it working now. In couple of minutes error occurs. ( I will check what is the exact time)

Anyway I have to mention, even with error the system does not stop working.
It continues works fine. But at every webSocket cicle it show that error.

**Comment by yurifontoura** [comment]
After 30 min error occurs

**Comment by alik0211** [comment]
@yurifontoura can you show me the code so I can reproduce the error?

**Comment by alik0211** [comment]
Fixed in version 3.2.0. More information about the new version — https://t.me/mtproto_core/18

**Comment by yurifontoura** [comment]
It is working after 3.2.0 fix! 

I've hidden console.warn in "~/src/rpc/index.js" that shows 'bad_server_salt'  in console because is not important at all.

Thank you Alik

**Comment by flaviolacer** [comment]
Hot this error after a certain time:

TypeError: Cannot read property 'type' of undefined
    at TLDeserializer.rpc_result (/app/telegram/node_modules/@mtproto/core/src/rpc/index.cjs:436:69)
    at TLDeserializer.predicate (/app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:163:41)
    at /app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:183:28
    at Array.forEach ()
    at TLDeserializer.predicate (/app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:165:26)
    at TLDeserializer.predicate (/app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:146:26)
    at /app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:183:28
    at Array.forEach ()
    at TLDeserializer.predicate (/app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:165:26)
    at RPC.handleEncryptedMessage (/app/telegram/node_modules/@mtproto/core/src/rpc/index.cjs:466:38)

**Comment by alik0211** [comment]
@flaviolacer This error will probably disappear after the next major version is released.
