### ISSUE TITLE
Trying to figure out how to use the API on NodeJS

### ISSUE THREAD

**Issue by velsa** [alik0211/mtproto-core#53]
Looked around issues, your docs, and official telegram docs, but I still can't figure out how to call the API with parameters.

I was able to use your `sendCode/signIn` example to successfully log in from my nodejs app. Also, some of the methods work fine (those without parameters). E.g. `messages.getAllChats` successfully returned all channels that I have. 

But methods with parameters are a mystery to me. For example, if I want to call `channels.getParticipants`, If I try to do it like this

```js
result = await mtproto.call('channels.getParticipants', {channel: channel.id});
console.log(result);
```

I get an error:

```
(node:12192) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_' of undefined
    at TLSerializer.predicate (/Users/vels/dev/tfeed/node_modules/@mtproto/core/src/tl/serializer/index.cjs:130:71)
    at /Users/vels/dev/tfeed/node_modules/@mtproto/core/src/tl/serializer/index.cjs:81:12
    at Array.forEach (<anonymous>)
    at TLSerializer.method (/Users/vels/dev/tfeed/node_modules/@mtproto/core/src/tl/serializer/index.cjs:68:23)
    at RPC.call (/Users/vels/dev/tfeed/node_modules/@mtproto/core/src/rpc/index.cjs:462:16)
    at MTProto.call (/Users/vels/dev/tfeed/node_modules/@mtproto/core/src/index.cjs:75:28)
    at /Users/vels/dev/tfeed/src/index.js:35:30
    at Array.forEach (<anonymous>)
    at /Users/vels/dev/tfeed/src/index.js:34:14
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:12192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I even tried do it like that:

```js
result = await mtproto.call('channels.getParticipants', {
  filter: {
    _: 'channelParticipantsAdmins',
  },
  offset: 0,
  limit: 40,
  hash: 0,
  channel: {
    _: 'inputChannel',
    channel_id: channel.id,
  },
  });
  console.log(result);
});
```
But this time I got:

```
(node:12249) UnhandledPromiseRejectionWarning: #<Object>
(node:12249) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12249) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I do realize that I am doing it completely wrong and would be thankful to see the correct way to transform API specs into API calls.

Thank you!

**Comment by velsa** [comment]
Any updates?
Let me know if you need more information. I am ready to make a small donation to progress with the issue. I think you library is great and has a lot of potential.
Lmk, please)

**Comment by alik0211** [comment]
Thanks for the issue! I plan to make playground by the end of the summer so that I can generate code for all methods.

Also, this week I will add an example for `channels.getParticipants` for you.

**Comment by timasplin** [comment]
@velsa The following worked for me:
`const result = await mtproto.call('channels.getParticipants', {
    channel: {
     _: 'inputChannel', 
    channel_id: channel.id, 
    access_hash: channel.access_hash
  },
  filter: {
    _: 'channelParticipantsAdmins',
  },
  offset: 0,
  limit: 40,
  hash: 0,
});
console.log({result});`

**Comment by alik0211** [comment]
@velsa, code by @timasplin work for you?

**Comment by velsa** [comment]
Hey, yes, thanks a lot!
Just got to testing it. It does work and now I'm able to run other methods as well.

Still, not all types and constructions in the protocol are obvious and official telegram docs are very cryptic (e.g. https://core.telegram.org/mtproto/TL-combinators#conditional-fields). I wonder if it's by design :)

Btw, I love your idea of the playground! But if we could have more docs and examples of using the various types and/or how do read/decrypt the telegram docs - it would be priceless.

Thanks for your hard work and support.

**Comment by gino8080** [comment]
how to get channel.access_hash ?
