### ISSUE TITLE
Add info about the result of the quick-start

### ISSUE THREAD

**Issue by Amantel** [alik0211/mtproto-core#57]
After launching quick-start (https://github.com/alik0211/mtproto-core#quick-start) I started to receive (after a huge time span of nothing) this info: 
```
Auth data is located in /home/tel/.local/share/@mtproto/core

Transport error:

Object {type: "socket"}
     type:"socket"

```
it does not look like a correct response, but I am not sure what I should expect. Should data come faster? Should there be no Transport error?

**Comment by alik0211** [comment]
@Amantel you use nodejs or browser? Call `help.getNearestDc` returned the result?

**Comment by Amantel** [comment]
Sorry for failing to provide more info.
My rig is: 
Linux (Kubuntu 18)
NodeJS (v8.7.0)

help.getNearestDc returned nothing. I have a debug point there, but nothing trigger it.

**Comment by alik0211** [comment]
@Amantel use nodejs 12 and higher. Telegram blocked in you country?

**Comment by Amantel** [comment]
Jepp, it is. Damn, I should probably use some proxies, right? 
Ahh, that's irritating

**Comment by alik0211** [comment]
Yes, if Telegram blocked in you country you should use proxy

**Comment by Amantel** [comment]
Thanks! I could not find a guidance in the repo on how to use proxy with this. 
I have tried on AWS server and everything works.
