### ISSUE TITLE
Custom transport

### ISSUE THREAD

**Issue by zzdhidden** [alik0211/mtproto-core#59]
I want to use websocket in node because the tcp transport does not support proxy agent.
Can you please provide a custom transport api ?

websocket in node with agent support: `new require('ws')(this.url, 'binary', {agent: agent})`

**Comment by zzdhidden** [comment]
Maybe the api like this: 
`new MTProto({transportClass, transportOptions})`

**Comment by alik0211** [comment]
Use a proxy at the system level.

**Comment by zzdhidden** [comment]
@alik0211 I mean the http and socks v5 proxy. net.socket does not support this.
