### ISSUE TITLE
lib breaks when trying to call api methods without logging in

### ISSUE THREAD

**Issue by Sparkenstein** [alik0211/mtproto-core#60]
It's expected behaviour as user should not call any api method that requires api-keys. but library needs to handle such error cases. 
This is the stack trace I get when I call the method `messages.getDialogs`. 

```sh
Uncaught (in promise) TypeError: Cannot read property '_' of undefined
    at TLSerializer.predicate (index.js:132)
    at index.js:81
    at Array.forEach (<anonymous>)
    at TLSerializer.method (index.js:68)
    at RPC.call (index.js:585)
    at index.js:388
    at Array.forEach (<anonymous>)
    at RPC.sendWaitMessages (index.js:386)
    at RPC.handleTransportOpen (index.js:96)
    at Socket.emit (events.js:152)
```
All I did was call `mtproto.call("messages.getDialogs")` the first thing when app starts to check if the user is logged in. 

apart from this error there's one more error like below
```
Uncaught (in promise) Error: invalid plaintext size (must be multiple of 16 bytes)
    at ModeOfOperationIGE.encrypt (index.js:33)
    at RPC.sendEncryptedMessage (index.js:646)
    at :40992/async http:/localhost:40992/bundle.js:25129
```
I debugged this error, the `plaintext` was of type `Uint8Array(234)`

**Comment by alik0211** [comment]
What params did you specify for the method `messages.getDialogs`? Show the code in which this method is called.

**Comment by Sparkenstein** [comment]
that was the method, no params:
```js
const dialogs = await mtproto.call("messages.getDialogs");
```

**Comment by alik0211** [comment]
You **must** pass parameters because they are specified in the API - https://core.telegram.org/method/messages.getDialogs#parameters

See example - https://github.com/alik0211/mtproto-core/issues/39#issuecomment-623125987

**Comment by Sparkenstein** [comment]
Yes I understand, It's not an **bug** as I said earlier, but library is not handling errors properly only. It's fairly common to call APIs incorrectly. but it should not break the library. that was my point :smiley:
