### ISSUE TITLE
Missing type definitions

### ISSUE THREAD

**Issue by sh-a-v** [alik0211/mtproto-core#63]
Can you publish type definitions `index.d.ts` to npm, please?

**Comment by totoblabla3** [comment]
+

**Comment by alik0211** [comment]
Made in version 3.4.0. Let me know if something is wrong

**Comment by sh-a-v** [comment]
@alik0211 there is an error in this [line](https://github.com/alik0211/mtproto-core/commit/337fafdbbbb2370d17c52a0efecdf63003db3831#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R29)
It should be `index.d.ts` not `.js`

**Comment by alik0211** [comment]
@sh-a-v Yes, you're right! Thank you very much, I will fix it in the next version.
