### ISSUE TITLE
Window and localStorage can be undefined

### ISSUE THREAD

**Issue by sh-a-v** [alik0211/mtproto-core#64]
`window` is undefined in a webworker process and `localStorage` is undefined in a browser private mode.
Can you add checks for these cases?

**Comment by alik0211** [comment]
Did. If you use [`customLocalStorage`](https://github.com/alik0211/mtproto-core#customlocalstorage-localstorage) library don't use `window.localStorage`. Commit - https://github.com/alik0211/mtproto-core/commit/6dd1481ba747550485e6ed4a6314547fcd93170a

A stable release will be announced in the channel — https://t.me/mtproto_core
