### ISSUE TITLE
A small issue in deserializer: this.data should be replaced with this.dataView

### ISSUE THREAD

**Issue by alexvorobyov** [alik0211/mtproto-core#67]
Hi! Thank you very much for your library.

Used it first time today and found a small issue in the deserialiser code [here](https://github.com/alik0211/mtproto-core/blob/master/src/tl/deserializer/index.js#L56): instead of 

```
const value = this.data.getFloat64(this.offset, true);
```

it should be:

```
const value = this.dataView.getFloat64(this.offset, true);
```

Not sure how it went unnoticed for a long time, seems like that method is not called often.

**Comment by alik0211** [comment]
Thank you for your attention! Fixed.
