### ISSUE TITLE
RAM consumption goes infinite when reading multiple channels

### ISSUE THREAD

**Issue by franklinzerocr** [alik0211/mtproto-core#68]
i am using the library to read 5+ channels periodically and the RAM consumption goes and goes and goes (memory leak). The server had to kill the process when it reached 2gb of consumption. So i had to create a clock process to kill and restart the telegram process.
With more channels it consumes it more rapidly too

**Comment by alik0211** [comment]
What methods do you use to read channels?

**Comment by franklinzerocr** [comment]
I get the channel's settings from this and store them
```
dialogs = await telegram.call('messages.getDialogs', {
        limit: parseInt(config.getChat.limit,20),
        offset_peer: {_: 'inputPeerEmpty'},    
      });
```

Then i read the channel with this method periodically, every 1.333 secs from 5+ different channels
```
let history = await telegram.call('messages.getHistory', {
            peer: {
            _: 'inputPeerChannel',
            channel_id: chatSettings.id,
            access_hash: chatSettings.access_hash
            },
            limit: limit,
            max_id: -offsetId,                            
        })  
```

**Comment by alik0211** [comment]
You need to work with `call` in a different way. Get responses first and then call the next `call`

**Comment by iamDonkey** [comment]
@alik0211  @franklinzerocr  i am also facing same issue on a similar use case and the node process gets auto killed by kernel. i think we need to investigate this for possible memory leaks.

**Comment by alik0211** [comment]
@iamDonkey Can you show your code?

**Comment by iamDonkey** [comment]
i saw ram usage spikes when it gets transport errors on socket. does the request get re-executed or ignored when transport error occurs?

**Comment by alik0211** [comment]
Transport errors are not currently processed. What transport errors do you have?

**Comment by iamDonkey** [comment]
Transport error: error code 429 i think its because of excessive requests, i also noticed error on socket but of type transport no code was shown.
memory gets full only when these errors occurs.
i reduced the speed/number of requests now seems stable.  i will send exact error details soon.

**Comment by iamDonkey** [comment]
![image](https://user-images.githubusercontent.com/65915198/100548777-ac2b4e80-3294-11eb-9df9-f1b9fc76f013.png)
@alik0211

**Comment by iamDonkey** [comment]
![image](https://user-images.githubusercontent.com/65915198/100548822-fe6c6f80-3294-11eb-8914-933de9cb837e.png)
