### ISSUE TITLE
serverless nodejs localstorage path issue

### ISSUE THREAD

**Issue by BDCode2020** [alik0211/mtproto-core#69]
Currently if I want to deploy on Vercel or AWS Lambda serverless environment, I will encounter this error: no such file or directory, mkdir '/home/sbx_user1051/.local/share/@mtproto/core' due to the initialization of the MTProto class from envPaths.  Serverless environment usually only supports /tmp directory.

Can you change it to not initiate the local storage while importing. The storage should only be initialized after the new MTProto() is called, this way we can pass customLocalStorage and overwrite the path to /tmp.

**Comment by alik0211** [comment]
Did. Commit - https://github.com/alik0211/mtproto-core/commit/6dd1481ba747550485e6ed4a6314547fcd93170a

A stable release will be announced in the channel — https://t.me/mtproto_core

**Comment by BDCode2020** [comment]
Thank you!
