### ISSUE TITLE
Cannot grab full user data

### ISSUE THREAD

**Issue by RJM94** [alik0211/mtproto-core#70]
```
const mtproto = new MTProto({ api_id, api_hash })
const fullUser = mtproto.call('users.getFullUser', { user_id, id: { _: 'inputUserSelf' } }, {})
    .then(result => console.log(result)).catch((error) => console.log(error))
```

Hello, I'm just trying to get the full user data for users.  Whenever I input my api_id and the api_hash and try to get the user data, I get an error saying: 

```
{ _: 'rpc_error', 
  error_code: 401, 
  error_message: 'AUTH_KEY_UNREGISTERED' } 
```

Is there something I am missing in here to be able to fully utilize the methods in `call` ?

**Comment by alik0211** [comment]
You need to log in. Guide - https://github.com/alik0211/mtproto-core/blob/master/docs/authentication.md
