### ISSUE TITLE
How to call "users.getUsers" method?

### ISSUE THREAD

**Issue by Sparky-web** [alik0211/mtproto-core#71]
I get stuck at calling users.getUsers, TG docs says that i should put Vector<InputUser> type in id field, but whai is it? I tried to play around the params and still getting nothing. 

`mtproto.call("users.getFullUser", {
    id: {
        _: "vector",
        type: "inputUser",
        user_id: 438670811
    }
})`

And getting 
{ _: 'rpc_error', error_code: 400, error_message: 'INPUT_FETCH_ERROR' }

Can you help me? What i should put in params in that case?

**Comment by alik0211** [comment]
Example for `users.getFullUser`:
```js
const result = await mtproto.call('users.getFullUser', {
  id: {
    _: 'inputUser',
    user_id: user_id,
    access_hash: access_hash,
  },
});
```

Example for `users.getUsers`:
```js
const result = await mtproto.call('users.getUsers', {
  id: [
    {
      _: 'inputUser',
      user_id: user_id,
      access_hash: access_hash,
    },
  ],
});
```
