### ISSUE TITLE
Help on writing JS to read Messages from a specific chat/ broadcast

### ISSUE THREAD

**Issue by TechnoTew** [alik0211/mtproto-core#72]
Beginner to this library, not really sure how it works besides having to call one of Telegram's methods.
Could anyone point me in the direction of how this works? For example, having to input this/ that as a parameter, finding chat ID.
I'm not really sure and any help would be appreciated

**Comment by alik0211** [comment]
Perhaps you need these methods:
1. [`messages.getDialogs`](https://core.telegram.org/method/messages.getDialogs)
2. [`messages.getHistory`](https://core.telegram.org/method/messages.getHistory)

**Comment by TechnoTew** [comment]
Okay thanks, but could I request for some sample code? I had errors calling message.getDialogs method

**Comment by alik0211** [comment]
Example for message.getDialogs: https://github.com/alik0211/mtproto-core/issues/39#issuecomment-623125987

**Comment by TechnoTew** [comment]
> Example for message.getDialogs: [#39 (comment)](https://github.com/alik0211/mtproto-core/issues/39#issuecomment-623125987)

`const { MTProto } = require('@mtproto/core');
const { resourceUsage } = require('process');

const api_id = '<filled in>';
const api_hash = '<filled in>';

// 1. Create an instance
const mtproto = new MTProto({
  api_id,
  api_hash,
});

// // 2. Get the user country code
// mtproto.call('help.getNearestDc').then(result => {
//   console.log(`country:`, result);
// });



mtproto.call('messages.getDialogs', { limit: 1, offset_peer : {
  _: 'inputPeerEmpty'
}}).then(result => {
  console.log(result);
}).catch(err => console.log(err));

` my code

thene it just gives me back this error:
`{
  _: 'rpc_error',
  error_code: 401,
  error_message: 'AUTH_KEY_UNREGISTERED'
}`

**Comment by alik0211** [comment]
You need to log in: https://github.com/alik0211/mtproto-core/blob/master/docs/authentication.md

**Comment by TechnoTew** [comment]
> You need to log in: https://github.com/alik0211/mtproto-core/blob/master/docs/authentication.md

Then what is the code and password about?

**Comment by alik0211** [comment]
1. The code comes to you from Telegram in the app or via SMS.
2. The password is used if you have 2FA enabled.

**Comment by TechnoTew** [comment]
> 1. The code comes to you from Telegram in the app or via SMS.
> 2. The password is used if you have 2FA enabled.

I have no 2FA but I didn't receive any code from telegram after running the auth code

**Comment by TechnoTew** [comment]
I have received the code, what do I do with it in the main program?

**Comment by alik0211** [comment]
Be considerate.

![image](https://user-images.githubusercontent.com/16985862/86798889-5aceb880-c082-11ea-96ac-e6e0c01db55d.png)

**Comment by TechnoTew** [comment]
Sorry haha that wasn't what I meant, 
after running that code with the correct code there are still errors like
```
{
  _: 'rpc_error',
  error_code: 401,
  error_message: 'AUTH_KEY_UNREGISTERED'
}
auth.authorization: {
  _: 'auth.authorizationSignUpRequired',
  pFlags: {},
  flags: 1,
  terms_of_service: {
    _: 'help.termsOfService',
    pFlags: {},
    flags: 0,
    id: {
      _: 'dataJSON',
      data: '{"country":"SG","min_age":false,"terms_key":"TERMS_OF_SERVICE","terms_lang":"en","terms_version":1,"terms_hash":"7dca806cb8d387c07c778ce9ef6aac04"}'
    },
    text: 'By signing up for Telegram, you agree not to:\n' +
      '\n' +
      '- Use our service to send spam or scam users.\n' +
      '- Promote violence on publicly viewable Telegram bots, groups or channels.\n' +
      '- Post pornographic content on publicly viewable Telegram bots, groups or channels.\n' +
      '\n' +
      'We reserve the right to update these Terms of Service later.',
    entities: []
  }
}
```

**Comment by alik0211** [comment]
`auth.authorizationSignUpRequired` means that your number is not registered in Telegram

**Comment by TechnoTew** [comment]
Weird then, I received the code and my number works in telegram for a while now
I guess my numbers broken
Thanks for all the help.
