### ISSUE TITLE
How to upload big files using Buffer

### ISSUE THREAD

**Issue by aykuxt** [alik0211/mtproto-core#73]

**Comment by alik0211** [comment]
Use the Telegram documentation — https://core.telegram.org/api/files#uploading-files

Or wait (I don't know how long) until I write a guide.

**Comment by VityaSchel** [comment]
> Use the Telegram documentation — https://core.telegram.org/api/files#uploading-files
> 
> Or wait (I don't know how long) until I write a guide.

can you write a guide already please?
