### ISSUE TITLE
Type definitions are not included in the package

### ISSUE THREAD

**Issue by darekaze** [alik0211/mtproto-core#74]
I notice that there is index.d.ts in the project, but when I install and import the package it shows "Could not find a declaration file for module '@mtproto/core'.". And when I dig into 'node_modules/@mtproto/code', there is no index.d.ts.

Currently a workaround is to copy the index.d.ts into that folder, a fix is appreciated to include the types in future release of the package.

**Comment by alik0211** [comment]
You're right. The file with types was not published in npm. I will add it in future releases

**Comment by alik0211** [comment]
https://t.me/mtproto_core/21
