### ISSUE TITLE
Constructor Vector

### ISSUE THREAD

**Issue by SergeyRyzhkov** [alik0211/mtproto-core#75]
--

**Comment by alik0211** [comment]
Please, use English.

**Comment by SergeyRyzhkov** [comment]
First of all, thank you for your excellent work !!!

Please tell me an example of how to work with Vector ?

As an example I want to call the method
**messages.getAllChats**

For example, creating a parameter:
```
const params = {
    except_ids: {
      **_: 'vector#1'**
    }
  };
```

But I get an error

**Comment by alik0211** [comment]
A vector is an array. Example params for **messages.getAllChats**:
```js
const params = {
  except_ids: [1, 2, 3]
};
```
