### ISSUE TITLE
multiple accounts online

### ISSUE THREAD

**Issue by wind-hx** [alik0211/mtproto-core#77]
Multiple accounts online, How to select an account to send messages?

**Comment by alik0211** [comment]
What does "Multiple accounts online" mean?

**Comment by wind-hx** [comment]
@alik0211 Multiple accounts call auth.signIn, and then call messages.sendMessage, how to distinguish accounts

**Comment by alik0211** [comment]
Support for multiple Telegram accounts is not implemented in the library. But you can use the [customLocalStorage](https://github.com/alik0211/mtproto-core#customlocalstorage-localstorage) for this purpose.

**Comment by bigbigsir** [comment]
How to use CustomLocalStorage, has resolved the distinction of multiple accounts

**Comment by Jo-Chris** [comment]
I always receive PEER_ID_INVALID when sending messages after i switched from Account A to Account B (at runtime). Could you help me out? Can we initialize a new Mtproto object at runtime and just proceed?
