### ISSUE TITLE
Channel data

### ISSUE THREAD

**Issue by amindotb** [alik0211/mtproto-core#80]
Hi, How can i get a Telegram channel data and posts ?

**Comment by alik0211** [comment]
Hi. Perhaps the [messages.getHistory](https://core.telegram.org/method/messages.getHistory) method will suit you.

**Comment by amindotb** [comment]
Thanks for your response. I tried to get data with following code:
`
const params = {
    id: {
      _: 'akhbarefori',
    },
};

mtproto.call('channels.getChannels',params).then(result => {
    console.log(`>>>:`, result);
  }).catch((err)=>{
    console.log("Error",err);
  });
`

But i got an error. Am i wrong ?

**Comment by alik0211** [comment]
The method [channels.getChannels](https://core.telegram.org/method/channels.getChannels) accepts a single **id** parameter. **id** is a vector. A vector is an array:
```js
const params = {
  id: [
    {
      _: 'inputChannel',
      channel_id: 12345,
      access_hash: '1234567890',
    },
    {
      _: 'inputChannel',
      channel_id: 12345,
      access_hash: '1234567890',
    },
  ],
};

mtproto.call('channels.getChannels', params).then(result => {
  console.log('result:', result);
});
```

**Comment by gino8080** [comment]
access_has should be the logged in user access_hash?

I keep getting CHANNEL_INVALID error

please give me a complete example
