### ISSUE TITLE
messages.getAllChats return INPUT_FETCH_ERROR

### ISSUE THREAD

**Issue by alexsanderluisdev** [alik0211/mtproto-core#82]
I'm trying to get all chats and I get this error:

`
{ _: 'rpc_error', error_code: 400, error_message: 'INPUT_FETCH_ERROR' }
`

My code:

```
const response = await api.call("messages.getAllChats", {

        except_ids: {

          _:  "vector",

        }

});
```

**Comment by alik0211** [comment]
You closed the issue, so I assume you found the problem. It's sad that you didn't share the decision with everyone. Then I'll do it.

The [messages.getAllChats](https://core.telegram.org/method/messages.getAllChats) method accepts only an **except_ids**. **except_ids** is a vector. A vector is an array:
```js
const params = {
  except_ids: [1, 2, 3],
};

mtproto.call('messages.getAllChats', params).then(result => {
  console.log('result:', result);
});
```
