### ISSUE TITLE
ERROR AUTH_RESTART

### ISSUE THREAD

**Issue by taogakiemtien** [alik0211/mtproto-core#84]
I use auth.sendCode, to log into multiple telegram accounts, if using the function for account B, when login is successful I use that function for account B, then this error appears. Then I try to get the entire message group of Message A and can't get it.
ERROR:

auth.sendCode error: { _: 'rpc_error', error_code: 500, error_message: 'AUTH_RESTART' }
(node:79262) UnhandledPromiseRejectionWarning: #<Object>
(node:79262) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:79262) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

Thank you very much.

**Comment by alik0211** [comment]
If you get AUTH_RESTART you need to make the [auth.sendCode](https://core.telegram.org/method/auth.sendCode) again (:

**Comment by mapacheverdugo** [comment]
I just opened the pull request #129 to solve this problem
