### ISSUE TITLE
Long polling

### ISSUE THREAD

**Issue by alshydev** [alik0211/mtproto-core#85]
Is it possible to add http_wait based long poll module?

**Comment by alik0211** [comment]
Can, but why? Long pool is terrible.

**Comment by alshydev** [comment]
Maybe another ways exists? For example, Telegram native methods of receiving messages?

**Comment by alik0211** [comment]
Sure. You can subscribe for updates — https://github.com/alik0211/mtproto-core#mtprotoupdatesonupdates-listener
