### ISSUE TITLE
Please, add more complex examples for better understanding

### ISSUE THREAD

**Issue by NickCashFlow** [alik0211/mtproto-core#87]
Ali, please, if it's not difficult for you, add some more complex examples of using the .call method, especially with parameters, because it's not entirely clear how this should work.
It would be nice to look at methods, messages.getHistory, messages.getMessages, messages.getMessagesReactions or any other more complex parameters. The community will be very grateful to you!

**Comment by alik0211** [comment]
I have plans for this.
