### ISSUE TITLE
Bug in TCP transport

### ISSUE THREAD

**Issue by softforseeker** [alik0211/mtproto-core#91]
Using this library I noticed that my application sometimes freezes. Note that I use a queue to execute requests.

After a little debugging, I found out that the matter is in the next line of code:

https://github.com/alik0211/mtproto-core/blob/c501692bc34bf61b63a850286ca788681bcd34cb/src/transport/tcp/index.js#L69-L75

It looks like telegram api going down (or another reason exists), tcp transport object close connection and initialize 1 more connection. As a result, promise, pending in this moment, going infinity. Then my queue get infinity waiting, because cannot receive result.

**Comment by q00n** [comment]
Hello, have the same issue. Is there any updates/solutions?

**Comment by alik0211** [comment]
What do you mean by "queue"?

**Comment by q00n** [comment]
> What do you mean by "queue"?

Job queue. In my case it's BULL (https://github.com/OptimalBits/bull)

**Comment by softforseeker** [comment]
All methods called one after another with random timeout.
Later i can do more deeper debug, but now problem is actual

**Comment by alik0211** [comment]
Thanks for the answers, guys! I plan more refactoring of the transport module + profiling for memory leaks

**Comment by iamDonkey** [comment]
@alik0211  i assume currently mtproto core uses intermediate protocol?
can you please add abridged version also? :thinking: 
also support for ipv6?
may be i could expect something like
`const mtproto = new MTProto({
    api_id: 12345,
    api_hash: 'abcdef0123456789',
ipv6: true,
tcp: 'abridged', 
});`  :thinking:

**Comment by Metallistener** [comment]
> Thanks for the answers, guys! I plan more refactoring of the transport module + profiling for memory leaks
@alik0211 Hi. Are you still planing to refactor Transport module?

**Comment by alik0211** [comment]
Network issues fixed in version 5.2.0 - https://t.me/mtproto_core/25

**Comment by afwn90cj93201nixr2e1re** [comment]
How we could reimplement some export stuff which are exists in tgdesktop app with using this library via nodejs?

@alik0211

**Comment by iamDonkey** [comment]
reimplement some export stuff means what exactly?

**Comment by afwn90cj93201nixr2e1re** [comment]
export stuff designed exclusively for tg desktop.

**Comment by alik0211** [comment]
@afwn90cj93201nixr2e1re I don't understand you.

**Comment by afwn90cj93201nixr2e1re** [comment]
Ok.

**Comment by iamDonkey** [comment]
Do you mean exporting chat history?

**Comment by afwn90cj93201nixr2e1re** [comment]
yes

**Comment by iamDonkey** [comment]
@alik0211 hi my friend,
can you please add these features?
-abridged transport
-ipv6

**Comment by alik0211** [comment]
@iamDonkey hi
1. Why do you need abridged transport?
2. Why do you need ipv6?

**Comment by iamDonkey** [comment]
abridged is simple,short and sweet compared to others. https://core.telegram.org/mtproto/mtproto-transports#abridged   The lightest protocol available.

Overhead: Very small

**Comment by alik0211** [comment]
The library currently uses [intermediate](https://core.telegram.org/mtproto/mtproto-transports#intermediate). I don't see the point of using an abridged.
