### ISSUE TITLE
Stop update new message after some time

### ISSUE THREAD

**Issue by yurifontoura** [alik0211/mtproto-core#94]
I've been working with mtproto in differents SO. Bytheway on Linux x64 (Ubuntu 20) it works well. But on Windows and Linux Arm (aarch64) it stop update new messages after some time. Now I really need it works on my jetson nano (aarch64).

Im going try to solve such problem by myself looking into source folder. In case of any success i will post here.

**Comment by alik0211** [comment]
To avoid missing new messages, you need to listen to all [Updates](https://core.telegram.org/type/Updates).

**Comment by yurifontoura** [comment]
Already did and in linux works pretty well. The problem only occurs on other OSs.
