### ISSUE TITLE
Keep getting AUTH_RESTART

### ISSUE THREAD

**Issue by CyberMew** [alik0211/mtproto-core#95]
I tried running the example code as per README, all seems fine, run it once, failed because the code is needed, so input that in, run it again, works great, authenticated.

Stop server, run it again, and I get AUTH_RESTART. So I have to stop and run it again to repeat the login process flow. Any idea how I can prevent this?

Also, how can I be notified whenever a message come in for any chat (group/private/channel)?

**Comment by alik0211** [comment]
You need to check whether you are logged in or not - https://github.com/alik0211/mtproto-core/issues/16#issuecomment-609359855

**Comment by CyberMew** [comment]
That was what I did and it says user is not logged in. Am I missing any other configuration?

**Comment by alik0211** [comment]
If the user is not logged in, then you need to log in))
