### ISSUE TITLE
How to get acess_hash

### ISSUE THREAD

**Issue by CodeVinc** [alik0211/mtproto-core#98]
```
const result = await mtproto.call('users.getUsers', {
  id: [
    {
      _: 'inputUser',
      user_id: user_id,
      access_hash: access_hash,
    },
  ],
})
```
I call GetUsers function, most i don't know like how get this, acess_hash and user_id number, how i get this? i am beginner in MTProtol.

**Comment by MoJongleur** [comment]
You will receive a set of this data in signIn
https://core.telegram.org/method/auth.signIn

user: { 
    _: 'user',
    pFlags: { self: true },
    flags: {some numbers},
    id: {your id},
    access_hash: {your access_hash},
    first_name: 'test',
    last_name: 'test',
    phone: {your phone},
    status: { _: 'userStatusOffline', was_online: 1600080688 }
  }
