### ISSUE TITLE
Send message to user

### ISSUE THREAD

**Issue by MoJongleur** [alik0211/mtproto-core#99]
I rummaged through all the documentation, but I could not find how to send a message to a specific user (by his id). Can you tell me?

Я перерыл всю документацию, но так и не смог найти как отправить сообщение конкретному пользователю( по его id ). Можете подсказать?

**Comment by MoJongleur** [comment]
The solution of the problem:

mtproto.call('messages.sendMessage', {
  peer: {
    _: 'inputPeerUser',
    user_id: {user_id}, 
    access_hash: '{user hash}'
  },
  message: "hello ",
  random_id: 1234
}).then(data => {
  console.log(data)
}).catch(errror => {
  console.log(errror)
})

**Comment by hAbd0u** [comment]
@MoJongleur How to get the '{user_id}' and '{user hash}'?

**Comment by MoJongleur** [comment]
> @MoJongleur How to get the '{user_id}' and '{user hash}'?

For example: https://core.telegram.org/method/channels.getParticipants

There you will get their hash and id.  In the morning I can throw off the example code

**Comment by TheRyan1** [comment]
@MoJongleur Any chance you have an example of how to retrieve the the user_ID and hash of a single contact in order to send them a message?

**Comment by pogudin-sergey** [comment]
> @MoJongleur Any chance you have an example of how to retrieve the the user_ID and hash of a single contact in order to send them a message?

```js
/**
 * Return user object for send message by username
 *
 * @param {object} client - Telegram class instance
 * @param {string} username - Telegram username
 * @returns {Promise<{user: object}>}
 * @throws {ApiError}
 */
async function getUserByUsername(client, username) {
  const userInfo = await client.call('contacts.resolveUsername', { username });
  const [user] = userInfo.users;
  return user;
}
```
